### ISSUE TITLE
[Bug]: 训练验证码速度板块的几个小bug

### ISSUE THREAD

**Issue by melon0918** [mikumifa/biliTickerBuy#105]
### 部署方式

release的打包文件

### 版本

2.7.8

### 异常情况

bug1:选择手动 首次点击开始测试 会一直卡住不显示验证码（控制台无输出，但有cpu占用）（选择使用接码网站rrocr则正常弹出）
![image](https://github.com/mikumifa/biliTickerBuy/assets/77735556/2bfa4818-6165-4371-b805-e53f081c7797)

bug2:如之前完成过一次验证码后 即使点击重新生成 生成的新验证码也会直接显示验证成功 无法手动去做了
![image](https://github.com/mikumifa/biliTickerBuy/assets/77735556/3f802e0e-7bab-4fc5-a86f-969823279ba6)

bug3（特性？）:无论是人工做验证码还是接码 在打码过程中软件cpu占用率相比前一版本会明显上升 本人cpu为7800x3d占用8%左右 不知是否是新功能所必须的亦或是出bug了![image](https://github.com/mikumifa/biliTickerBuy/assets/77735556/89059f86-f170-48c6-8303-db645902e3df)

**Comment by mikumifa** [comment]
不放心就先用老版吧，最近事多，bug没时间修

**Comment by melon0918** [comment]
辛苦了

**Comment by mikumifa** [comment]
修了，cpu占用率就不管了，性能不是程序的主要需求
