### ISSUE TITLE
[Feature]: 可否实现同时抢多个票或者抢完后继续下一个抢票

### ISSUE THREAD

**Issue by FairyWorld** [mikumifa/biliTickerBuy#106]
### 这是一个？

新功能

### 详细描述

目前配置文件只能写入一个抢票信息，假如要抢连续3天的同一个门票，就要复制三次每次，然后在抢票成功再粘贴抢下一张比较麻烦

**Comment by mikumifa** [comment]
b站不能分别购买不同种类的票

所以脚本也没有，实习这个功能回影响速度，没有必要
