### ISSUE TITLE
2024/7/20 广州萤火虫漫展实测可行

### ISSUE THREAD

**Issue by 8824PPZ** [mikumifa/biliTickerBuy#109]
![image](https://github.com/mikumifa/biliTickerBuy/assets/36729296/bc236405-566b-4c57-b34a-814d1187e856)
![image](https://github.com/mikumifa/biliTickerBuy/assets/36729296/599f258a-46e0-49d1-9e26-8c361b0d1150)
感谢大佬！！！
感谢大佬！！！
感谢大佬！！！

**Comment by mikumifa** [comment]
这个票很难抢吗

**Comment by mikumifa** [comment]
为啥不是整点，不太懂，还有与遇到验证码吗

**Comment by mikumifa** [comment]
因为我最近更新的一版，验证码是错的，我还好奇怎么用的上的😇
