### ISSUE TITLE
[Feature]:  本地自动过验证服务

### ISSUE THREAD

**Issue by Amorter** [mikumifa/biliTickerBuy#113]
### 这是一个？

现有功能优化

### 详细描述

看到加了两个打码平台的接口？

不过我这边已经做出了本地自动验证的船新版本
https://github.com/Amorter/biliTicker_gt

滑块验证码准确率接近100%
点选验证码准确率72%

缺点是速度相比云端平台稍慢，且目前需要附加一个exe文件，体积较大
是否要加入呢？

**Comment by Violiate** [comment]
我觉得有必要加入。用人人的话会受到网速影响，如果网速不好就得等好久

**Comment by mikumifa** [comment]
可以加上，后续会加

**Comment by mikumifa** [comment]
能抽象出一个http接口吗，和rrocr类似，输入gt和challenge，输出校验码

**Comment by Amorter** [comment]
> 能抽象出一个http接口吗，和rrocr类似，输入gt和challenge，输出校验码

![image](https://github.com/mikumifa/biliTickerBuy/assets/63935225/33c4f8bd-7a98-48f9-81dc-0239ea0070cc)
项目的第三个demo就是，省略register函数，直接填写gt和challenge再进行后续操作即可

**Comment by mikumifa** [comment]
目前整合了，速度很快，没啥缺点，不过要整合到当前项目还差一点东西

1.  2个exe文件要能自己设置，这样好打包
2. 基本上每次都成功，不成功的会有以下的报错，我不知道为什么
![image](https://github.com/mikumifa/biliTickerBuy/assets/99951454/c657ea50-6eb4-4a9a-8f1f-d80612d2181a)
项目的逻辑是，只要这个函数raise一个异常，就会retry，不过这个程序会一直raise这个异常，想知道这个异常有没有办法避免
还是程序哪里出问题了，测试时候发现，出现这个异常的时候，手工验证码打不开，

**Comment by mikumifa** [comment]
70% 2秒速度属于是有点逆天了

**Comment by Amorter** [comment]
> 目前整合了，速度很快，没啥缺点，不过要整合到当前项目还差一点东西
> 
> 1. 2个exe文件路径要能自己设置，这样好打包
> 2. 基本上每次都成功，不成功的会有以下的报错，我不知道为什么
>    ![image](https://private-user-images.githubusercontent.com/99951454/339809133-c657ea50-6eb4-4a9a-8f1f-d80612d2181a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzc0MzgsIm5iZiI6MTcxODM3NzEzOCwicGF0aCI6Ii85OTk1MTQ1NC8zMzk4MDkxMzMtYzY1N2VhNTAtNmViNC00YTlhLThmMWYtZDgwNjEyZDIxODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0NTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMGY0NjhkMDYyNTlhMzQzMGEyNDVkNzU5ODgzZDgyMDBjMThiNDkzNWRhNmViOGMyZGIxZGJlNmMxZjdjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R2fLkYLHfwSKOOG1neoU3Rx21exCxgxrYz059XgVFbk)
>    项目的逻辑是，只要这个函数raise一个异常，就会retry，不过这个程序会一直raise这个异常，想知道这个异常有没有办法避免
>    还是程序哪里出问题了，测试时候发现，出现这个异常的时候，手工验证码打不开，

我分析一下
data是最后的verify接口返回的，包含msg和validate，我这边只返回了validate
提示缺少validate哪里是识别失败了
你后面一直提示缺少date我猜想是报了old challenge错误，也就是说你是不是没刷新challenge和gt的情况下访问了get_type后面的接口
get_type()  get_new_c_s_args()
这俩接口在不更新challenge的情况下单验证流程只能访问一次
你可以在retry的时候跳过这两个接口

不过如果retry的时候图像不刷新的话好像识别还是必然失败
我逆向极验的时候没看图片是自动刷新的还是怎么样，这块你可能得自己测试一下

如果是手动刷新的话，你可以手动修改get_new_c_s_args()返回的args，那个args其实就是图片的url

**Comment by Amorter** [comment]
click.exe和slide.exe的问题
我正在尝试将js运行时整合进项目，有望取消这两个文件的外部依赖，请等待v0.2.0版本

**Comment by Amorter** [comment]
看到了，好像fali了是会发一个refresh请求
geetest_1718378245891({
    "status": "success",
    "data": {
        "spec": "1*1",
        "sign": "",
        "pic": "/captcha_v3/batch/v3/73400/2024-06-14T23/word/f297e0ab51184461afa16be4ae2238a5.jpg",
        "pic_type": "word",
        "num": 0,
        "image_servers": ["static.geetest.com/", "dn-staticdown.qbox.me/"]
    }
})

把image_servers和pic拼接一下赋给args就好了https://static.geetest.com//captcha_v3/batch/v3/73400/2024-06-14T23/word/f297e0ab51184461afa16be4ae2238a5.jpg

**Comment by mikumifa** [comment]
第一个缺少validate，可能是因为错了
后面都是因为重新访问就挂了

**Comment by Amorter** [comment]
> 访问就

是的，极验有些接口是不能同一个challenge多次访问的

**Comment by mikumifa** [comment]
具体应该怎么重试，感觉封装好的，不好改

**Comment by Amorter** [comment]
> 具体应该怎么重试，感觉封装好的，不好改

需要再加入一个接口，我本来想写一个demo，想想你现在加上去到时候我版本更新了你还要改代码，算了

先等我这边更新吧，我会加重试逻辑的，应该明早你就能看到了

**Comment by Amorter** [comment]
> 具体应该怎么重试，感觉封装好的，不好改

v0.2.0已发布，新增接口见README的自动重试部分，这一部分还是有极小概率出现错误(但是真的很小了，小于1%)。这块如果再出错就只能换challenge了

**Comment by mikumifa** [comment]
测试一下， 会稳定出现 0xC0000005 报错 Process finished with exit code -1073741819 (0xC0000005)

**Comment by Amorter** [comment]
> 测试一下， 会稳定出现 0xC0000005 报错 Process finished with exit code -1073741819 (0xC0000005)
我这边没问题，能建个分支让我fork一下吗

**Comment by Amorter** [comment]
> 测试一下， 会稳定出现 0xC0000005 报错 Process finished with exit code -1073741819 (0xC0000005)

只运行demo也会这样吗

**Comment by Amorter** [comment]
import bili_ticket_gt_python
import time
click = bili_ticket_gt_python.ClickPy()

start = time.time()
for i in range(100):
	(gt, challenge) = click.register_test("https://passport.bilibili.com/x/passport-login/captcha?source=main_web")
	validate = click.simple_match_retry(gt, challenge)
	print(validate)
	print(time.time() - start)

**Comment by mikumifa** [comment]
放线程里面运行会稳定报错
Process finished with exit code -1073741819 (0xC0000005)

**Comment by Amorter** [comment]
> 放线程里面运行会稳定报错 Process finished with exit code -1073741819 (0xC0000005)

能否给我一个稳定报错的最小化demo，这样我才能根据demo debug，因为实际上是用rust代码写的，这边python看不出来问题

**Comment by mikumifa** [comment]
import bili_ticket_gt_python
import loguru
import threading

from config import cookies_config_path
from geetest.Validator import Validator
from util.bili_request import BiliRequest


class AmorterValidator(Validator):
    def need_api_key(self) -> bool:
        return False

    def have_gt_ui(self) -> bool:
        return False

    def __init__(self):
        self.click = bili_ticket_gt_python.ClickPy()
        pass

    def validate(self, appkey, gt, challenge, referer="http://127.0.0.1:7860/") -> str:
        try:
            loguru.logger.info(f"gt: {gt} ; challenge: {challenge}")
            validate = self.click.simple_match_retry(gt, challenge)
            loguru.logger.info(f"validate: {validate}")
            return validate

        except Exception as e:
            loguru.logger.warning(e)
            raise e


if __name__ == "__main__":
    # 使用示例
    appkey = "xxxxxxxxxxxxxxxxxxx"
    _request = BiliRequest(cookies_config_path=cookies_config_path)
    test_res = _request.get(
        "https://passport.bilibili.com/x/passport-login/captcha?source=main_web"
    ).json()
    challenge = test_res["data"]["geetest"]["challenge"]
    gt = test_res["data"]["geetest"]["gt"]

    validator = AmorterValidator()
    try:
        def validate_task():
            validate_string = validator.validate(appkey, gt, challenge)
            print(f"Validation result: {validate_string}")

        # 创建一个线程来运行验证函数
        validation_thread = threading.Thread(target=validate_task)
        # 启动线程
        validation_thread.start()
    except Exception as e:
        print(f"Error: {e}")

**Comment by mikumifa** [comment]
```python
import bili_ticket_gt_python
import loguru
import threading

from config import cookies_config_path
from geetest.Validator import Validator
from util.bili_request import BiliRequest


class AmorterValidator(Validator):
    def need_api_key(self) -> bool:
        return False

    def have_gt_ui(self) -> bool:
        return False

    def __init__(self):
        self.click = bili_ticket_gt_python.ClickPy()
        pass

    def validate(self, appkey, gt, challenge, referer="http://127.0.0.1:7860/") -> str:
        try:
            loguru.logger.info(f"gt: {gt} ; challenge: {challenge}")
            validate = self.click.simple_match_retry(gt, challenge)
            loguru.logger.info(f"validate: {validate}")
            return validate

        except Exception as e:
            loguru.logger.warning(e)
            raise e


if __name__ == "__main__":
    # 使用示例
    appkey = "xxxxxxxxxxxxxxxxxxx"
    _request = BiliRequest(cookies_config_path=cookies_config_path)
    test_res = _request.get(
        "https://passport.bilibili.com/x/passport-login/captcha?source=main_web"
    ).json()
    challenge = test_res["data"]["geetest"]["challenge"]
    gt = test_res["data"]["geetest"]["gt"]

    validator = AmorterValidator()
    try:
        def validate_task():
            validate_string = validator.validate(appkey, gt, challenge)
            print(f"Validation result: {validate_string}")

        # 创建一个线程来运行验证函数
        validation_thread = threading.Thread(target=validate_task)
        # 启动线程
        validation_thread.start()
    except Exception as e:
        print(f"Error: {e}")

```

**Comment by mikumifa** [comment]
这感觉很微妙，我测试了线程和进程，都会挂

**Comment by Amorter** [comment]
> 这感觉很微妙，我测试了线程和进程，都会挂

确实是有问题，我目前正在debug，请稍后

**Comment by mikumifa** [comment]
那个是不是不好解决，我是想把rrocr和本地的验证码并发启动的，这样就算本地出错了，rrocr也能垫底（rrocr他可以访问别人访问过的接口）

**Comment by mikumifa** [comment]
2个结合就能100%过码了，还保证速度，最优解了

**Comment by Amorter** [comment]
> 那个是不是不好解决，我是想把rrocr和本地的验证码并发启动的，这样就算本地出错了，rrocr也能垫底（rrocr他可以访问别人访问过的接口）

刚刚有了新进展，马上就会发布新版本。
关于和手动并发的问题，其实这边也是可以并发的，仅仅只有几个接口是不能重复访问的，之前说过了是get_type和get_new_c_s_challenge，你如果程序保证这两个接口只访问一次理论也是可以并发的，不过我目前没时间处理相关逻辑

**Comment by Amorter** [comment]
> > 那个是不是不好解决，我是想把rrocr和本地的验证码并发启动的，这样就算本地出错了，rrocr也能垫底（rrocr他可以访问别人访问过的接口）
> 
> 刚刚有了新进展，马上就会发布新版本。 关于和手动并发的问题，其实这边也是可以并发的，仅仅只有几个接口是不能重复访问的，之前说过了是get_type和get_new_c_s_challenge，你如果程序保证这两个接口只访问一次理论也是可以并发的，不过我目前没时间处理相关逻辑

并发可能bw结束才会直接内嵌到我这边验证模块把

**Comment by mikumifa** [comment]
够用了

**Comment by Amorter** [comment]
> 够用了

0.2.1版本已经发布，解决了多线程问题

**Comment by mikumifa** [comment]
感觉这么好用的接码一出，当初技术选型选gradio就有点浪费了

当时选成网页版的一大原因就是因为要过验证码，觉得反正过验证码要开浏览器的，为什么不直接做成浏览器的网页版，现在感觉这个接码方式一出，应该没什么人用到手过验证码吧😂

**Comment by Amorter** [comment]
> 感觉这么好用的接码一出，当初技术选型选gradio就有点浪费了
> 
> 当时选成网页版的一大原因就是因为要过验证码，觉得反正过验证码要开浏览器的，为什么不直接做成浏览器的网页版，现在感觉这个接码方式一出，应该没什么人用到手过验证码吧😂

由于涉及到python, rust, js 等多种语言，有后期迁移到WASM平台的计划，而Edge浏览器恰好支持WASM运行，所以选型没有错误😭
