### ISSUE TITLE
[Bug]: 抢票停不下来了

### ISSUE THREAD

**Issue by melon0918** [mikumifa/biliTickerBuy#123]
### 部署方式

release的打包文件

### 版本

2.8.0

### 异常情况

开始抢票后点停止也停不下来了 跟吃了炫迈一样（
另建议将biliTicker_gt里那个onnx dll一起打包 缺了那个dll我的电脑上会无法运行（win10专业版 22H2）

**Comment by mikumifa** [comment]
v2.8.1 解决
