### ISSUE TITLE
[Bug]: 打包文件运行异常

### ISSUE THREAD

**Issue by ravizhan** [mikumifa/biliTickerBuy#125]
### 部署方式

release的打包文件

### 版本

v2.8.1

### 异常情况

缺少aiohttp模块

### 报错信息

![image](https://github.com/mikumifa/biliTickerBuy/assets/37010563/314cb097-e5eb-4c38-9a0e-ae93dbbb4941)

**Comment by mikumifa** [comment]
忘记加了，明天补回去
