### ISSUE TITLE
[Bug]: 本地过验证码功能异常

### ISSUE THREAD

**Issue by ravizhan** [mikumifa/biliTickerBuy#126]
### 部署方式

手动部署

### 版本

v2.8.1

### 异常情况

使用本地过验证码时，代码运行到此，无报错退出
https://github.com/mikumifa/biliTickerBuy/blob/601fd98532e800dbc04b6cc53a8ef86f1f43660b/geetest/AmorterValidator.py#L24
![image](https://github.com/mikumifa/biliTickerBuy/assets/37010563/d1d9efa9-1123-4518-8519-5ebff6e9975c)
经测试，该问题稳定触发

**Comment by ravizhan** [comment]
releases的版本也一样
![image](https://github.com/mikumifa/biliTickerBuy/assets/37010563/71093e7b-e578-4dd7-90f1-7441f9fa69e6)

**Comment by mikumifa** [comment]
@Amorter 0.2.3好像 线程里面不能调用的问题又出现了
Process finished with exit code -1073741819 (0xC0000005)

**Comment by Amorter** [comment]
> @Amorter 0.2.3好像 线程里面不能调用的问题又出现了 Process finished with exit code -1073741819 (0xC0000005)
我艹不可能啊，我看看

**Comment by Amorter** [comment]
> @Amorter 0.2.3好像 线程里面不能调用的问题又出现了 Process finished with exit code -1073741819 (0xC0000005)

奇了怪了，我只是增加了一个dll打包，怎么会出问题

**Comment by mikumifa** [comment]
那个ddl必要吗

**Comment by Amorter** [comment]
> 那个ddl必要吗

![image](https://github.com/mikumifa/biliTickerBuy/assets/63935225/1d65893b-6242-4060-824c-e7a4eba8c0b8)
大多数情况下，这是因为Windows自带的ONNX运行时版本(通常是旧版本)。确保您已将ONNX运行时dll复制到与exe相同的文件夹中。

参考https://github.com/mikumifa/biliTickerBuy/issues/121

**Comment by Amorter** [comment]
> @Amorter 0.2.3好像 线程里面不能调用的问题又出现了 Process finished with exit code -1073741819 (0xC0000005)

![image](https://github.com/mikumifa/biliTickerBuy/assets/63935225/6bb7fdd7-6efe-41c7-bfe3-a89bfd95e123)
我的demo未复现问题，
我试一下你的项目，稍微等一下

**Comment by Amorter** [comment]
![image](https://github.com/mikumifa/biliTickerBuy/assets/63935225/ce008509-f806-4622-9a53-fd75038a62ff)
我这边完全正常，我需要可以复现的环境

**Comment by mikumifa** [comment]
奇怪了，是2.8.1吗

**Comment by Amorter** [comment]
他这个退出代码不是线程问题，是内存安全问题，我明明用的rust，为什么会出现内存安全问题，我能想到我代码里没有完全安全的就那么几行，但我实在想不出哪里错了

**Comment by mikumifa** [comment]
用到那个ddl地方
加把锁？

**Comment by Amorter** [comment]
> 用到那个ddl地方 加把锁？

我认为不是多线程导致的内存共享问题，因为rust的编译器不允许我做出跨线程的不安全行为，你在子线程中调用我的simple_match_retry函数，本质上也没有多个线程一起调用，总感觉不是这个的问题

你有把办法复现author的报错吗

**Comment by mikumifa** [comment]
那我就先改成串行版本吧。

我机器是稳定出现这个问题

**Comment by Amorter** [comment]
> 那我就先改成串行版本吧。
> 
> 我机器是稳定出现这个问题

你能加入我们的qq群组吗，我们一直在群中讨论关于bili脚本和验证模块的问题818884376

**Comment by Amorter** [comment]
抱歉，忘了群搜索没有打开，请添加1270329917，他会将你拉入群聊

**Comment by woshiluo** [comment]
能给一下 windows 版本号和 python 版本号吗，我这边试试看复现一下

**Comment by ravizhan** [comment]
![image](https://github.com/mikumifa/biliTickerBuy/assets/37010563/37becc9d-c409-4e25-83fb-5daaf513c20d)

python是3.12.3

**Comment by Hoshino-Yumetsuki** [comment]
> > 用到那个ddl地方 加把锁？
> 
> 我认为不是多线程导致的内存共享问题，因为rust的编译器不允许我做出跨线程的不安全行为，你在子线程中调用我的simple_match_retry函数，本质上也没有多个线程一起调用，总感觉不是这个的问题
> 
> 你有把办法复现author的报错吗

可以试试直接用py而不是rust实现（

**Comment by ravizhan** [comment]
我在尝试直接逆向成python，但是以我的水平估计得搞个两三天。
估计等我搞好，上面两位大佬也修好了😂😂😂

**Comment by Amorter** [comment]
> y而不是rust实现（
> 等着抢bw

python实现也是一个解决方案，在很多问题上，他会解决很多！

不过我这里验证码项目的目标是全平台通用，所以选择了rust，以后如果有用其他语言实现的bli抢票脚本，也可以用我的库。

如果你能为biliTickerBuy单独创建一个python版本，是一个有趣的工作，感谢你的付出！

**Comment by mikumifa** [comment]
v2.8.2 解决

**Comment by ricky8955555** [comment]
![image](https://github.com/mikumifa/biliTickerBuy/assets/24487646/dbaaf6e0-f92d-41ef-8b49-ff1d05176658)

在 Linux 上使用 Python 3.11 在 main 分支上 https://github.com/mikumifa/biliTickerBuy/commit/7cf64a739c366f01c283c7af3b5917965958d1a8 在训练界面进行第二次验证码测试时会出现 SIGSEGV (Segfault, 段错误) 问题，使用通过 git 源安装主分支的 [biliTicker_gt](https://github.com/Amorter/biliTicker_gt) 仍能出现该问题。

**Comment by ricky8955555** [comment]
> ![image](https://private-user-images.githubusercontent.com/24487646/344368069-dbaaf6e0-f92d-41ef-8b49-ff1d05176658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2Mzk3NjYsIm5iZiI6MTcxOTYzOTQ2NiwicGF0aCI6Ii8yNDQ4NzY0Ni8zNDQzNjgwNjktZGJhYWY2ZTAtZjkyZC00MWVmLThiNDktZmYxZDA1MTc2NjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA1Mzc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZTllMGI5Zjc5ZDlhMDgzY2JiZmE5ZTU0MjA3MTFjYjI3OTJkZWQzMWJlNDAwNjY3NDc2ZDc3NGJkYTg0NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_eVOv4sU7LxFpW3pjASNpv4le2mbJgwm_H03IX97bc)
> 
> 在 Linux 上使用 Python 3.11 在 main 分支上 [7cf64a7](https://github.com/mikumifa/biliTickerBuy/commit/7cf64a739c366f01c283c7af3b5917965958d1a8) 在训练界面进行第二次验证码测试时会出现 SIGSEGV (Segfault, 段错误) 问题，使用通过 git 源安装主分支的 [biliTicker_gt](https://github.com/Amorter/biliTicker_gt) 仍能出现该问题。

![image](https://github.com/mikumifa/biliTickerBuy/assets/24487646/95a284ff-d001-4748-826e-6a7b3b2173ea)
通过 rust-gdb 调试猜测是跟调用 V8 相关部分的问题
