### ISSUE TITLE
[Bug]: rrocr过码失效

### ISSUE THREAD

**Issue by YourComputer011** [mikumifa/biliTickerBuy#130]
### 部署方式

手动部署

### 版本

v2.8.2

### 异常情况

rrocr自动过码失效，但可以在rrocr选项下手动过码，除此之外手动过码正常，本地过码正常，capsolver未测试。
v2.8.0版本测试rrocr自动过码正常

**Comment by mikumifa** [comment]
好好，mark，下次迭代修

**Comment by mikumifa** [comment]
fix了
