### ISSUE TITLE
本地验证日志返回[Feature]: 

### ISSUE THREAD

**Issue by iftditelsegvup** [mikumifa/biliTickerBuy#150]
### 这是一个？

现有功能优化

### 详细描述

2024-06-22 06:50:24.527 | INFO     | geetest.AmorterValidator:validate:20 - AmorterValidator gt: ac597a4506fee079629df5d8b66dd4fe ; challenge: 7ea7100463168f249729d06404e69157
2024-06-22 06:50:26.982 | INFO     | geetest.AmorterValidator:validate:22 - AmorterValidator: f3b32752c8c39dbdb7025a9f68e28e86
网页显示
 {
code:  100003,
message:  "验证码过期",
ttl:  1,
data:  null
}
这样是本地验证模块部署好了吗
请教下如何部署https://github.com/Amorter/biliTicker_gt/releases
本地库已经装好
import bili_ticket_gt_python
slide = bili_ticket_gt_python.SlidePy()
click = bili_ticket_gt_python.ClickPy()
通过slide和click调用相关函数
这三条没看很懂 
大一新生 还不熟悉git，还请多加指点
谢谢

**Comment by WittF** [comment]
> 2024-06-22 06:50:24.527 | INFO | geetest.AmorterValidator:validate:20 - AmorterValidator gt: ac597a4506fee079629df5d8b66dd4fe ; challenge: 7ea7100463168f249729d06404e69157 2024-06-22 06:50:26.982 | INFO | geetest.AmorterValidator:validate:22 - AmorterValidator: f3b32752c8c39dbdb7025a9f68e28e86 网页显示 { code: 100003, message: "验证码过期", ttl: 1, data: null } 这样是本地验证模块部署好了吗 

返回validate并显示过期就是过码成功了，仓库里的代码和[Release](https://github.com/mikumifa/biliTickerBuy/releases)都是已经添加Amorter的本地过码了，还要部署啥

**Comment by iftditelsegvup** [comment]
过码的时候没有图像界面是正常的吗 过码的过程看不见 
请问想看看测试效果该怎么办 谢谢

**Comment by WittF** [comment]
> 过码的时候没有图像界面是正常的吗 过码的过程看不见 请问想看看测试效果该怎么办 谢谢

只有手动才会显示验证框，其他几个都是返回validate，看时间就行了

**Comment by iftditelsegvup** [comment]
好的，谢谢您的答复 感谢您无私的开源精神



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月23日(周日) 上午7:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mikumifa/biliTickerBuy] 本地验证日志返回[Feature]:  (Issue #150)




  
过码的时候没有图像界面是正常的吗 过码的过程看不见 请问想看看测试效果该怎么办 谢谢
  
只有手动才会显示验证框，其他几个都是返回validate，看时间就行了
