### ISSUE TITLE
可能有延迟吧，反正我抢到之后就跳二维码了

### ISSUE THREAD

**Issue by QWERTYRDSDFGsdfghFDYDEFG** [mikumifa/biliTickerBuy#152]
可能有延迟吧，反正我抢到之后就跳二维码了

_Originally posted by @mikumifa in https://github.com/mikumifa/biliTickerBuy/issues/55#issuecomment-2072032804_

**Comment by WittF** [comment]
？

**Comment by MUSESTAR-Official** [comment]
?

**Comment by mikumifa** [comment]
关了，看不懂
