### ISSUE TITLE
[Feature]: APP的是否可以抢呢？

### ISSUE THREAD

**Issue by aikangkang** [mikumifa/biliTickerBuy#158]
### 这是一个？

新功能

### 详细描述

您好，有的问题想问下，辛苦看下哈

如下图，今年bw似乎有行提示《为了更好的购票体验，请您前往哔哩哔哩App购买》，我忘记了这个是每年都这样还是今年才这样的，是不是代表着不能用pc端只能用APP抢票了，这种情况下有试过脚本是否可用吗？
![image](https://github.com/mikumifa/biliTickerBuy/assets/62366202/ed5abc60-e07d-4377-abdc-699c9ca82ed2)

**Comment by Colin-Chen630** [comment]
[#76](https://github.com/mikumifa/biliTickerBuy/discussions/76)

**Comment by aikangkang** [comment]
好的，多谢兄弟，close啦。
