### ISSUE TITLE
[Bug]: 抢票成功，但程序进入死循环无法关闭

### ISSUE THREAD

**Issue by wlz-remake** [mikumifa/biliTickerBuy#16]
### 部署方式

release的打包文件

### 系统环境

Windows 10

### 异常情况

实际已抢票成功，但提示失败
之后程序不断尝试继续抢票，无法停止
关闭全部窗口后仍在后台运行 继续不停抢票

### 报错信息

![2OW~7RB9 V4H29M_9QNI`73](https://github.com/mikumifa/biliTickerBuy/assets/105090141/52efd0b1-1d50-48d3-80dd-6eb729505d41)

**Comment by mikumifa** [comment]
最新版已解决问题
