### ISSUE TITLE
[Bug]: 多开进程的账号登录问题

### ISSUE THREAD

**Issue by lllllis-02** [mikumifa/biliTickerBuy#167]
### 部署方式

手动部署

### 版本

v2.8.4

### 异常情况

我想要部署两个进程来完成对两天的抢票，但是今天复查的时候发现已经登录的两个账号自动同步成了一个。例：目录F:\2024bw\bilibili-buy_1进程登陆了账号1，F:\2024bw\bilibili-buy_2登陆了账号2，今天都变成账号1了，再次重新登录2后又全部变更成了2。

**Comment by lllllis-02** [comment]
登录后刷新网页就会变更至同一登录信息，所以可能登录后不能再刷新了？

**Comment by lllllis-02** [comment]
找了一个展测试了一下，发现虽然在程序2登录的账号名称变成了1，但是实际票归属是在2。所以大概只是一个小bug?

**Comment by lllllis-02** [comment]
> 2个进程的`bilibili-buy.exe`在同一目录吗

我把他们放在了F:\2024bw目录下，再分为两个文件夹
![image](https://github.com/mikumifa/biliTickerBuy/assets/156657335/6d05649e-df9d-43f6-a5b4-614ea0f228f3)

**Comment by WittF** [comment]
刚试了一下，没复现

**Comment by mikumifa** [comment]
不能是同一个软件，多复制几个分别打开

**Comment by lllllis-02** [comment]
> 不能是同一个软件，多复制几个分别打开

我复制了两个，在截图里能看到，但还是会串

**Comment by mikumifa** [comment]
你在仔细检查一下，应该是你使用问题

**Comment by mikumifa** [comment]
还是没问题的话，给出详细的复现的步骤

**Comment by lllllis-02** [comment]
> 你在仔细检查一下，应该是你使用问题

我目前没发现哪里有问题，我试试看放到不同盘。如果还不行也不是什么大问题，虽然显示是一个名字，但是票的实际归属是两个账号分开的
