### ISSUE TITLE
[Feature]: 多账号、多商品抢票？

### ISSUE THREAD

**Issue by wlz-remake** [mikumifa/biliTickerBuy#17]
### 这是一个？

新功能

### 详细描述

有没有考虑过（）
因为大伙七八个人想抱团去，像cp这种一个账号只能买两张票，而且有的人想去第一天有的人想去第二天

**Comment by mikumifa** [comment]
官网好像一次订单只能买一种票

**Comment by mikumifa** [comment]
提前准备好配置文件即可
