### ISSUE TITLE
[Bug]: 抢未开售的票时，程序没有任何输出

### ISSUE THREAD

**Issue by wlz-remake** [mikumifa/biliTickerBuy#18]
### 部署方式

release的打包文件

### 系统环境

Windows 10

### 异常情况

如题程序窗口信息输出框里没有任何反应

**Comment by mikumifa** [comment]
没开售票没办法抢啊

**Comment by mikumifa** [comment]
实际上已经开始抢了, 最新版添加了提示信息 #
