### ISSUE TITLE
[Feature]: BW无法电脑端买票了，请问购票的url应该如何得到呢？

### ISSUE THREAD

**Issue by Sherlockliu7777** [mikumifa/biliTickerBuy#185]
### 这是一个？

新功能

### 详细描述

BW无法电脑端买票了，请问购票的url应该如何得到呢？

**Comment by WittF** [comment]
BW 
https://show.bilibili.com/platform/detail.html?id=85939

BML 
https://show.bilibili.com/platform/detail.html?id=85938
