### ISSUE TITLE
[Bug]: bw抢票异常

### ISSUE THREAD

**Issue by lllllis-02** [mikumifa/biliTickerBuy#227]
### 部署方式

手动部署

### 版本

v2.8.4

### 异常情况

![image](https://github.com/mikumifa/biliTickerBuy/assets/156657335/7282e0ca-a16d-44cf-a467-3d558b7f0c5d)
如图，当时一直提示抢票出现问题请查看控制台，貌似是因为1000的速度太快了？我设置的是12.00.4的自动定时

**Comment by lllllis-02** [comment]
结局是13,14双战败呜呜呜呜呜

**Comment by mikumifa** [comment]
挤不进去

**Comment by lllllis-02** [comment]
> 挤不进去

oh所以和手机端提示拥挤是一样的，程序按照这样设置可以运行？我还以为是一次抢两个人导致的冲突

**Comment by mikumifa** [comment]
大家都挤不进去
