### ISSUE TITLE
[Bug]: 抢票次数过多后，web-ui会崩溃，显示此页面存在问题

### ISSUE THREAD

**Issue by Mapleawaa** [mikumifa/biliTickerBuy#228]
### 部署方式

release的打包文件

### 版本

v2.8.5

### 异常情况

![image](https://github.com/mikumifa/biliTickerBuy/assets/143710505/e28e942f-bf47-400a-b1fe-a6b7185d51d5)
## 如图 运行大约两个小时后，Web-UI会提示页面出现问题，刷新后界面恢复，继续抢票后故障依旧
![image](https://github.com/mikumifa/biliTickerBuy/assets/143710505/e5292aff-c181-41f2-ab1b-4970e5b22ebe)

**Comment by lllllis-02** [comment]
为啥你的每一个订单都能发送呜呜呜我的根本挤不进去

**Comment by lllllis-02** [comment]
你的时间间隔是多少啊

**Comment by Mapleawaa** [comment]
> 为啥你的每一个订单都能发送呜呜呜我的根本挤不进去

3000

**Comment by mikumifa** [comment]
程序没崩就 可能是其他原因

**Comment by Mapleawaa** [comment]
> 程序没崩就 可能是其他原因

:p 懂了
