### ISSUE TITLE
[Bug]: 提示时间格式不正确

### ISSUE THREAD

**Issue by akie001** [mikumifa/biliTickerBuy#249]
### 部署方式

release的打包文件

### 版本

V2.8.4

### 异常情况

![QQ截图20240629171445](https://github.com/mikumifa/biliTickerBuy/assets/94307990/6ddc1892-9c76-4524-8d0a-7bef60d35632)
请问这是开票前正常的吗

**Comment by mikumifa** [comment]
最新版

**Comment by mikumifa** [comment]
下载最新版
