### ISSUE TITLE
BW2024实测可行

### ISSUE THREAD

**Issue by index20481** [mikumifa/biliTickerBuy#257]
![Screenshot_20240629_181929_tv danmaku bili](https://github.com/mikumifa/biliTickerBuy/assets/77374137/934e4122-13d5-4a2a-ad6f-ab02dba3e61c)
真的是万分感谢大大了！！！！！

**Comment by miaowuawa** [comment]
电信的网，五点多测验证码还是好的，开前三四分钟测试就开始SSL handshake有问题，过一会又好了，过一会又炸，然后抢票的时候又报错了……大家最好还是多个设备多个网络一起吧

**Comment by zunduwuyu** [comment]
what？？？可以说下配置信息吗？？为什么我就被封号了呢？？（就是打开什么票都显示前方拥挤，即便是有很多余票的其他展）

**Comment by index20481** [comment]
> what？？？可以说下配置信息吗？？为什么我就被封号了呢？？（就是打开什么票都显示前方拥挤，即便是有很多余票的其他展）

好家伙还有这事😑，我就正常按步骤配好定时抢票，验证码还是我自己手动的...你不会提前抢了吧...

**Comment by mikumifa** [comment]
感觉脚本也很迷，稍微有点奇怪的输入就可能出问题
