### ISSUE TITLE
[Bug]: 控制台和浏览器不会自动关闭

### ISSUE THREAD

**Issue by Eric-Lee-DT** [mikumifa/biliTickerBuy#26]
### 部署方式

release的打包文件

### 系统环境

Windows11

### 异常情况

在选择配置选项时弹出Edge窗口和控制台，登录成功后自动关闭；配置完成后回到选项界面选择第二个选项（已完成配置，开始抢票选项时）会再次弹出Edge窗口和控制台，此时浏览器内已经登录成功，浏览器和控制台窗口不会自动关闭。截图是控制台的显示内容，有两串好像是IP的东西？我遮盖了一下，如果需要的话可以发出来。保持控制台和Edge窗口开启，抢票功能好像能继续使用；按CTRL+C复制控制台内容后控制台和浏览器窗口闪退，之后抢票功能不能使用。
![CMD_PRT](https://github.com/mikumifa/biliTickerBuy/assets/160200707/ea744503-97ba-4bd8-b6da-102f97c491d0)

**Comment by mikumifa** [comment]
那个是找滑块的
