### ISSUE TITLE
[Bug]: 选择实名人信息点击提交后无反应

### ISSUE THREAD

**Issue by sun-health217** [mikumifa/biliTickerBuy#27]
### 部署方式

手动部署

### 系统环境

Window11

### 异常情况

点击提交后就没反应了，不会生成配置信息，没发生无响应等情况

**Comment by xYeahx** [comment]
请问问题解决了吗

**Comment by sun-health217** [comment]
并没有，还是选择了实名人信息之后点击提交就无反应了，等超过五分钟还是没有配置信息

**Comment by kui-king** [comment]
我的也是这样子，使用旧版就不会有问题

**Comment by sun-health217** [comment]
运行main.py后通过查看命令行得到报错信息如下：
![screenshot-1712735717389](https://github.com/mikumifa/biliTickerBuy/assets/121806344/e75d54c6-56ab-4313-8ac3-f17f76c4a9a3)

**Comment by mikumifa** [comment]
#28
