### ISSUE TITLE
[Feature]: 视频

### ISSUE THREAD

**Issue by kui-king** [mikumifa/biliTickerBuy#28]
### 这是一个？

现有功能优化

### 详细描述

在选择收货地址界面选中人后点击提交无法继续，代码报错为：    
nonlocal delivery_info
                    ^^^^
IndexError: list index out of range
不知道是不是我使用问题，希望您可以再出个简单的视频教程。
很抱歉提出该要求，该项目设计的太多数代码没有涉及过，因此并不了解问题在哪。谢谢。

**Comment by mikumifa** [comment]
遗留bug， 要填一下收货地址，收货地址随便找一个商品填一下就可以了
