### ISSUE TITLE
[Feature]: 未知错误代码100079，指的是有本人的未支付订单导致无法抢票

### ISSUE THREAD

**Issue by Teeedy** [mikumifa/biliTickerBuy#290]
### 这是一个？

现有功能优化

### 详细描述

这是在抢今天bml时发现的问题
当出现本人未支付订单时，即使场次不同也会阻止你买票
![github](https://github.com/mikumifa/biliTickerBuy/assets/69799905/a1998928-82f5-40da-8279-1cf0bd50c4c4)

**Comment by mikumifa** [comment]
所以抢不同票时候要开不同的好。。
正常下单应该也会这样吧，一个没付款是不能下单的

**Comment by mikumifa** [comment]
最新版补一个参数，应该解决这个问题了

**Comment by Teeedy** [comment]
> 最新版补一个参数，应该解决这个问题了

看到修改的内容了，感谢大大！

**Comment by ZianTT** [comment]
奇了怪了，那我给补哪去了🤔

**Comment by mikumifa** [comment]
你那个加上去报错
应该是1

**Comment by ZianTT** [comment]
> 你那个加上去报错 应该是1

那没事了
