### ISSUE TITLE
[Feature]: 这个脚本文件，能不能抢限制用APP抢的票？

### ISSUE THREAD

**Issue by lewic-web** [mikumifa/biliTickerBuy#30]
### 这是一个？

新功能

### 详细描述

因为我想抢的票是限定在手机端购买的，但是我用您写的这个软件也是能查到场次信息，以及能完成配置，并且能设置抢票时间的，所以我想确认一下，是不是说也能抢
![d379985d12cefd60b2778ab0295c895](https://github.com/mikumifa/biliTickerBuy/assets/155031936/a2409843-8a1a-4e11-9d2e-c2dda6260e5d)

**Comment by mikumifa** [comment]
没见过， 说不定可以

**Comment by lewic-web** [comment]
> 没见过， 说不定可以

好的，我过几天试一试

**Comment by YanRuiMing** [comment]
我猜你想抢星铁的票（狗头，我希望B站没有锁手机端

**Comment by lewic-web** [comment]
> 我猜你想抢星铁的票（狗头，我希望B站没有锁手机端

是的，哈哈哈

**Comment by shengengqing** [comment]
星铁票应该可以

**Comment by MqKeYan** [comment]
验证根本不弹出

**Comment by lewic-web** [comment]
> 验证根本不弹出

什么弹不出验证

**Comment by MqKeYan** [comment]
感觉可以试试把APP的网页提取出来，APP提取的网页仍然可以用，只是PC识别码的网页不能用（来个大佬看看能不能把这个突破了）

**Comment by EmoriMiku** [comment]
这个PC端手动打开的话是可以通过edge→右上角“...”→更多工具→开发人员工具→切换设备仿真（Ctrl+Shift+M）实现手机模拟的，如果能把这一步自动化...蹲个大佬
![mobile - A](https://github.com/mikumifa/biliTickerBuy/assets/167228937/0eefa90c-e39a-4e3d-a204-785ba71cceeb)

**Comment by EmoriMiku** [comment]
或者用edge的开发人员工具进行设备仿真。如果把这一步自动化...蹲个大佬

**Comment by YanRuiMing** [comment]
> 没见过， 说不定可以

亲测可以，就是需要自己在手机上点验证码，点过之后脚本就不会被验证码卡住，可以正常下单。可以关闭这个issues了，感谢作者（

**Comment by doxsw** [comment]
用手机端分享链接就能在电脑上打开了
![image](https://github.com/mikumifa/biliTickerBuy/assets/143856673/8029e62b-26bb-4c88-b61a-1d12182217e8)
https://mall.bilibili.com/mall-dayu/neul-next/ticket/detail.html?id=84096&from=itemshare&noTitleBar=1&share_source=&share_medium=android&bbid=759031E4-B8F6-B67F-186D-856D81369B4F69505infoc&ts=1713358406517

**Comment by miracle-2-3** [comment]
> > 没见过,说不定可以
> 
> 亲测可以,就是需要自己在手机上点验证码,点过之后脚本就不会被验证码卡住,可以正常下单。可以关闭这个问题了,感谢作者（

我没太明白是怎么样的流程 想问一下老师抢到了吗 可以指导一下吗 孩子在等第二波

**Comment by lewic-web** [comment]
今天实践了，是能够抢的，没问题的。

**Comment by miracle-2-3** [comment]
> 今天实践了，是能够抢的，没问题的。

可以讲一下流程吗 或者和博主发的这个有修改的地方  是不需要改 直接按说明做 还是用下面那个链接做调整 孩子真的笨

**Comment by lewic-web** [comment]
> > 今天实践了，是能够抢的，没问题的。
> 
> 可以讲一下流程吗 或者和博主发的这个有修改的地方 是不需要改 直接按说明做 还是用下面那个链接做调整 孩子真的笨

就按照做着的方法来，如果你被验证码卡住了，你就可以用手机去点一下验证码。

**Comment by schoolbag123** [comment]
> > > 今天实践了，是能够抢的，没问题的。
> > 
> > 
> > 可以讲一下流程吗 或者和博主发的这个有修改的地方 是不需要改 直接按说明做 还是用下面那个链接做调整 孩子真的笨
> 
> 就按照做着的方法来，如果你被验证码卡住了，你就可以用手机去点一下验证码。

是要打开手机端，然后如果弹重新验证，手机端会立马弹出相关的验证窗口吗？

**Comment by OWwWO** [comment]
另一个项目已经解决手机端抢票问题了

**Comment by schoolbag123** [comment]
那个项目现在开始收费了，一天40块钱，不保证能抢到并且有被风控的风险

**Comment by schoolbag123** [comment]
> > 另一个项目已经解决手机端抢票问题了
> 
> 指条路，能放个链接吗？
那个项目现在开始收费了，一天40块钱，不保证能抢到并且有被风控的风险

**Comment by lewic-web** [comment]
> > > 另一个项目已经解决手机端抢票问题了
> > 
> > 
> > 指条路，能放个链接吗？
> 
> 那个项目现在开始收费了，一天40块钱，不保证能抢到并且有被风控的风险

还挺黑的

**Comment by mikumifa** [comment]
别急，最近事多，后面会更新的

**Comment by OWwWO** [comment]
> > 另一个项目已经解决手机端抢票问题了
> 
> 指条路，能放个链接吗？

https://github.com/Just-Prog/Bilibili_show_ticket_auto_order

**Comment by mikumifa** [comment]
> > > 另一个项目已经解决手机端抢票问题了
> > 
> > 指条路，能放个链接吗？
> 亲测可以，这个项目更新的内容是拿着参数自己去生成极验验证码，并且走的app的抢票接口，可以参考下
> https://github.com/Just-Prog/Bilibili_show_ticket_auto_order

那下一次加上去
