### ISSUE TITLE
[Bug]: 软件打不开

### ISSUE THREAD

**Issue by yushenzhiren** [mikumifa/biliTickerBuy#31]
### 部署方式

release的打包文件

### 系统环境

win11

### Python环境

3.12

### 异常情况

只能打开抢票选项，到配置选项时，输入id之后无法调用edge浏览器，弹一下命令行就没反应了，打开开启抢票选项，是空白界面，啥都没有

**Comment by mikumifa** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/?form=MA13LH
下一下这个
