### ISSUE TITLE
[Bug]: 输入商品id后弹出弹窗后弹窗立马关闭，程序重回抢票选项窗口

### ISSUE THREAD

**Issue by Tangxier** [mikumifa/biliTickerBuy#32]
### 部署方式

手动部署

### 系统环境

Win11

### 异常情况

输入商品id后弹出弹窗后弹窗立马关闭，程序重回抢票选项窗口
很抱歉临时抱佛脚，对程序及使用并不熟悉，望寻求解答，感激不尽

**Comment by mikumifa** [comment]
看一下这个#31
