### ISSUE TITLE
[Bug]: KeyError: 'token'

### ISSUE THREAD

**Issue by LollipopGeneral** [mikumifa/biliTickerBuy#329]
### 部署方式

release的打包文件

### 版本

bilibili-buy_v2.8.5-patch.2

### 异常情况

开始抢票后，提示 当前错误"token" 
已经登录过，日志如图

### 报错信息

![20240701132818](https://github.com/mikumifa/biliTickerBuy/assets/45588935/bc20c2b8-ffa8-4e64-a373-26877abc226f)

**Comment by 131A3D7** [comment]
你选择抢的票已经停止售卖了，所以不能抢。在选择页面注意自己选择要抢的票后面的tag不能是不可售（选了就会报错误token）
![image](https://github.com/mikumifa/biliTickerBuy/assets/78592363/1318f524-6ac0-49b2-826d-b3b7d18f74fe)

**Comment by LollipopGeneral** [comment]
不可售状态/无法购买状态 都是不能抢是吧，明白了。
可以把错误提示改一下，我还以为是token原因
