### ISSUE TITLE
[Bug]: 验证已超时，请重新验证弹不出来验证窗口

### ISSUE THREAD

**Issue by Glorysmith233** [mikumifa/biliTickerBuy#33]
### 部署方式

release的打包文件

### 系统环境

WINDOWS11

### 异常情况

开抢之后显示验证已超时，请重新验证，
![QQ截图20240416142900](https://github.com/mikumifa/biliTickerBuy/assets/167170133/a57aead2-f8e2-41fa-a520-62355ce2ebc6)
但是弹出的浏览器没有任何可以验证的东西，切换账号也不行

**Comment by tes223** [comment]
同是第一天嘉年华票抢不到的沦落人（）

**Comment by MqKeYan** [comment]
哈哈哈，大家都一样，凄惨的故事

**Comment by MqKeYan** [comment]
那个滑块验证没有弹出说白了

**Comment by MqKeYan** [comment]
这个网页只是限制了pc，APP里面的分享依然可以提取出可用网页版（这可能是一个APP封锁的突破口！）

**Comment by Glorysmith233** [comment]
急急急死我了呜呜

**Comment by TouchedOVO** [comment]
抢其他的票有些直接就能发送成功，有些就要验证，急。让我们来看看人工队的表现

**Comment by MqKeYan** [comment]
怎么样阿

**Comment by GYF0814** [comment]
主要是没有办法手动验证就很难受

**Comment by MqKeYan** [comment]
确实

**Comment by MqKeYan** [comment]
那个滑块验证内部才有解决

**Comment by MqKeYan** [comment]
说白了，B站今年没有开放后门，后门给黄牛那些了

**Comment by GYF0814** [comment]
急急急急急急急急

**Comment by MqKeYan** [comment]
一样急，但是没有办法

**Comment by GYF0814** [comment]
看了一下wiki，应该是作者写的时候没见过抢票的时候会出现滑块，但是写的时候理论上是可以人工过验证的，但是不知道为什么滑块出不来，可能是因为叔叔把网页端ban了的原因，还有就是刚刚在其他issue也看到了一个理论可以的解决方法就是把app里的链接提取出来

**Comment by Glorysmith233** [comment]
> 看了一下wiki，应该是作者写的时候没见过抢票的时候会出现滑块，但是写的时候理论上是可以人工过验证的，但是不知道为什么滑块出不来，可能是因为叔叔把网页端ban了的原因，还有就是刚刚在其他issue也看到了一个理论可以的解决方法就是把app里的链接提取出来

那链接有啥用呢？？电脑可以抢吗还是

**Comment by GYF0814** [comment]
> > 看了一下wiki，应该是作者写的时候没见过抢票的时候会出现滑块，但是写的时候理论上是可以人工过验证的，但是不知道为什么滑块出不来，可能是因为叔叔把网页端ban了的原因，还有就是刚刚在其他issue也看到了一个理论可以的解决方法就是把app里的链接提取出来
> 
> 那链接有啥用呢？？电脑可以抢吗还是

为了过滑块（？

**Comment by Glorysmith233** [comment]
> > > 看了一下wiki，应该是作者写的时候没见过抢票的时候会出现滑块，但是写的时候理论上是可以人工过验证的，但是不知道为什么滑块出不来，可能是因为叔叔把网页端ban了的原因，还有就是刚刚在其他issue也看到了一个理论可以的解决方法就是把app里的链接提取出来
> > 
> > 
> > 那链接有啥用呢？？电脑可以抢吗还是
> 
> 为了过滑块（？

唉唉，星铁可以抢不到 bw别给我整这出啊 我要四了

**Comment by TouchedOVO** [comment]
这个仅限手机端就是为了防我们这些散户脚本狗的（），一般来说高级点的黄牛都拿内部票了

**Comment by TouchedOVO** [comment]
手机浏览器也可以抢手机端专属的，也许可以修改浏览器UA标识进入手机端网页发送请求

**Comment by MqKeYan** [comment]
> 看了一下wiki，应该是作者写的时候没见过抢票的时候会出现滑块，但是写的时候理论上是可以人工过验证的，但是不知道为什么滑块出不来，可能是因为叔叔把网页端ban了的原因，还有就是刚刚在其他issue也看到了一个理论可以的解决方法就是把app里的链接提取出来

那个提取就是我说的

**Comment by MqKeYan** [comment]
电脑浏览器依然可可以直接打开APP的网页版

**Comment by MqKeYan** [comment]
但是改变不了咱抢不到票的现状。

**Comment by TouchedOVO** [comment]
但是抢到不锁票噢，因为手机端的逻辑就是跳转支付宝微信直接支付，你还是会慢一步

**Comment by GYF0814** [comment]
> 电脑浏览器依然可可以直接打开APP的网页版

直接开应该是被拦截了，改了ua就正常
![图片](https://github.com/mikumifa/biliTickerBuy/assets/88437660/b311040a-656e-45e8-a4f9-090275795ab0)

**Comment by MqKeYan** [comment]
> > > > 看了一下wiki，应该是作者写的时候没见过抢票的时候会出现滑块，但是写的时候理论上是可以人工过验证的，但是不知道为什么滑块出不来，可能是因为叔叔把网页端ban了的原因，还有就是刚刚在其他issue也看到了一个理论可以的解决方法就是把app里的链接提取出来
> > > 
> > > 
> > > 那链接有啥用呢？？电脑可以抢吗还是
> > 
> > 
> > 为了过滑块（？
> 
> 唉唉，星铁可以抢不到 bw别给我整这出啊 我要四了

还有一种说法，今年抢票要慢慢点不能点快了

**Comment by MqKeYan** [comment]
点快了好像要被杀

**Comment by MqKeYan** [comment]
> 但是抢到不锁票噢，因为手机端的逻辑就是跳转支付宝微信直接支付，你还是会慢一步

就是这个我卡了好多次，去年也是

**Comment by TouchedOVO** [comment]
但是你浏览器跳转不到支付宝，如果你用的手机UA，大概会跳转到支付宝app下载页面

**Comment by MqKeYan** [comment]
不

**Comment by Glorysmith233** [comment]
> > > > > 看了一下wiki，应该是作者写的时候没见过抢票的时候会出现滑块，但是写的时候理论上是可以人工过验证的，但是不知道为什么滑块出不来，可能是因为叔叔把网页端ban了的原因，还有就是刚刚在其他issue也看到了一个理论可以的解决方法就是把app里的链接提取出来
> > > > 
> > > > 
> > > > 那链接有啥用呢？？电脑可以抢吗还是
> > > 
> > > 
> > > 为了过滑块（？
> > 
> > 
> > 唉唉，星铁可以抢不到 bw别给我整这出啊 我要四了
> 
> 还有一种说法，今年抢票要慢慢点不能点快了

我去，真的假的 我每次点的超快都抢不到

**Comment by MqKeYan** [comment]
去年脚本抢票会锁票

**Comment by Glorysmith233** [comment]
对，去年脚本会锁

**Comment by MqKeYan** [comment]
卡支付应该也是被锁了

**Comment by MqKeYan** [comment]
今年其实有新脚本，但是内部不对外

**Comment by TouchedOVO** [comment]
今年不锁吧
你去翻人家实录视频，抢600档的付款慢了显示无票

**Comment by MqKeYan** [comment]
说白了后门是留给B站黄牛代拍的

**Comment by TouchedOVO** [comment]
慢慢点？你是说顶像无感验证？

> > > > > > 看了一下wiki，应该是作者写的时候没见过抢票的时候会出现滑块，但是写的时候理论上是可以人工过验证的，但是不知道为什么滑块出不来，可能是因为叔叔把网页端ban了的原因，还有就是刚刚在其他issue也看到了一个理论可以的解决方法就是把app里的链接提取出来
> > > > > 
> > > > > 
> > > > > 那链接有啥用呢？？电脑可以抢吗还是
> > > > 
> > > > 
> > > > 为了过滑块（？
> > > 
> > > 
> > > 唉唉，星铁可以抢不到 bw别给我整这出啊 我要四了
> > 
> > 
> > 还有一种说法，今年抢票要慢慢点不能点快了
> 
> 我去，真的假的 我每次点的超快都抢不到

**Comment by MqKeYan** [comment]
点快了会把验证冲掉

**Comment by MqKeYan** [comment]
而且今年好像不是滑块验证了，是文字

**Comment by GYF0814** [comment]
https://www.hiczp.com/wang-luo/mo-ni-bilibili-android-ke-hu-duan-deng-lu.html
模拟 Bilibili Android 客户端

**Comment by TouchedOVO** [comment]
文字一般都是顶像无感验证，搞太快会被当成机器人的

**Comment by MqKeYan** [comment]
我今天点掉了几次验证，就是因为重复点快了

**Comment by TouchedOVO** [comment]
主要就是想捡漏，等2批次发下来高铁酒店贵的飞起，也就没有去的必要了，况且能不能打赢3.2万人关注的复活赛还另说

**Comment by Glorysmith233** [comment]
> 主要就是想捡漏，等2批次发下来高铁酒店贵的飞起，也就没有去的必要了，况且能不能打赢3.2万人关注的复活赛还另说

最难打的一集

**Comment by GYF0814** [comment]
> 主要就是想捡漏，等2批次发下来高铁酒店贵的飞起，也就没有去的必要了，况且能不能打赢3.2万人关注的复活赛还另说

复活赛已经打算手点了（

**Comment by MqKeYan** [comment]
主要是咱不能让黄牛得逞

**Comment by TouchedOVO** [comment]
你现在这情况也没法脚本了，除非C语言大佬（阴险）（

**Comment by MqKeYan** [comment]
闲鱼上一堆代拍，真恶心

**Comment by MqKeYan** [comment]
家人们找到解决方法了戳一下

**Comment by gy1041** [comment]
所以现在这个脚本是用不了了是吗

**Comment by TouchedOVO** [comment]
事，app专属的票各凭本事吧

> 所以现在这个脚本是用不了了是吗

**Comment by starctopkok** [comment]
额，我还想着今天抢崩铁嘉年华的票

**Comment by YanRuiMing** [comment]
亲测可以抢崩铁，就是需要自己在手机上点验证码，点过之后脚本就不会被验证码卡住，可以正常下单。

**Comment by Kocurrrrrr** [comment]
请问是得在想买的票那个页面点验证码吗？想买崩铁嘉年华回流票的，很难刷出来可以弹验证码的界面

**Comment by YanRuiMing** [comment]
> 请问是得在想买的票那个页面点验证码吗？想买崩铁嘉年华回流票的，很难刷出来可以弹验证码的界面

是，所以脚本比较难抢回流

**Comment by JYK89** [comment]
啊 我手动没抢到 还指望脚本能帮我抢到呢
