### ISSUE TITLE
大佬，现在b站验证码机制好像更改了，有什么办法解决吗

### ISSUE THREAD

**Issue by zhang-clup** [mikumifa/biliTickerBuy#35]
### 这是一个？

新功能

### 详细描述

现在b站滑块验证弹不出来，好像改为了文字验证抢票

**Comment by mikumifa** [comment]
没见过接口长啥样，现在要是有其他商品是那个验证码的，我就能添加这个feature，但是找不到这样的物品

**Comment by YUkinoevwe** [comment]
> 没见过接口长啥样，现在要是有其他商品是那个验证码的，我就能添加这个feature，但是找不到这样的物品

明日方舟嘉年华用的是新验证

**Comment by mikumifa** [comment]
> > 没见过接口长啥样，现在要是有其他商品是那个验证码的，我就能添加这个feature，但是找不到这样的物品
> 
> 崩铁嘉年华用的也是新验证

这几个很快就抢完了，来不及爬，见不到接口

**Comment by CaoMeiYouRen** [comment]
> > > 没见过接口长啥样，现在要是有其他商品是那个验证码的，我就能添加这个feature，但是找不到这样的物品
> > 
> > 
> > 崩铁嘉年华用的也是新验证
> 
> 这几个很快就抢完了，来不及爬，见不到接口

感觉是只有在手机端限定的票有这个限制

**Comment by mikumifa** [comment]
目前来看是[这个](https://github.com/kuresaru/geetest-validator?tab=readme-ov-file)，能再现一次接口请求，手机抓包就能解决

**Comment by Ezarke** [comment]
大佬为啥我输入id提交之后，只出现了命令窗口，命令窗口上啥也没有，然后就直接关掉了

**Comment by Ezarke** [comment]
![Uploading `}9W[$`X3@4@T3JM3VX91@H.png…]()

**Comment by mikumifa** [comment]
执行解决了
