### ISSUE TITLE
[Feature]: 使用已售罄票种尝试提前通过验证码

### ISSUE THREAD

**Issue by gpc123456** [mikumifa/biliTickerBuy#352]
### 这是一个？

新功能

### 详细描述

使用已售罄票种尝试提前通过验证码

**Comment by gpc123456** [comment]
嗯嗯，是的，不过这个时间具体是多少还不太确定，需要明天再详细测试一下

**Comment by mikumifa** [comment]
单独写一个独立的tab？

如果这个能避免抢票时候验证码的话

手抢或者机器都能收益

**Comment by gpc123456** [comment]
嗯嗯是的，我也觉得再开一个tab比较好，或许可以叫”验证码预填“，供大家在合适的情况下选择使用。

而且修改的话感觉逻辑也不是特别复杂，可以复用正常抢票的逻辑，但去掉循环只发送一次请求即可

**Comment by ZianTT** [comment]
建议多提前一点去过带验证码的项目，否则出现“账号异常不允许购票”有可能开票后被“请慢一点哟”青蒜

**Comment by gpc123456** [comment]
> 建议多提前一点去过带验证码的项目，否则出现“账号异常不允许购票”有可能开票后被“请慢一点哟”青蒜

是这样的，感谢提醒！

**Comment by Colin-Chen630** [comment]
> 建议多提前一点去过带验证码的项目，否则出现“账号异常不允许购票”有可能开票后被“请慢一点哟”青蒜

多提前一些不会超过白名单的时间吗

**Comment by gpc123456** [comment]
> > 建议多提前一点去过带验证码的项目，否则出现“账号异常不允许购票”有可能开票后被“请慢一点哟”青蒜
> 
> 多提前一些不会超过白名单的时间吗
我这边今天测试了几次，平均这个状态能持续10-15分钟，再长的话就需要重新验证了。我打算将这个提前时间设置为一个可修改的参数，大家可以根据自己的实际情况来修改
