### ISSUE TITLE
[Bug]:  BiliRequest 所有函数调用时添加意外实参 timeout=1，至少会导致无法获取当前登陆用户名

### ISSUE THREAD

**Issue by jhzgjhzg** [mikumifa/biliTickerBuy#365]
### 部署方式

手动部署

### 版本

v2.8.6-patch.1

### 异常情况

登陆但是不显示用户名，排查一下发现是 BiliRequest 所有函数调用时添加意外实参 timeout=1，去除后至少用户名可以正常显示。感觉是某次修改的时候出现typo了？虽然还没用到 BiliRequest.get 和 BiliRequest.post，不过应该也会出现影响。

**Comment by gpc123456** [comment]
有时B站会长时间不发回请求会导致抢票脚本卡死，因此在昨天的pr中添加了`timeout`参数。当时没注意排查出来这个问题，现在来看是有这样的问题，或许`timeout`的值还需要再测试一下，看看能不能够修复。

**Comment by gpc123456** [comment]
找到问题所在了，我现在修复一下，感谢您提出这个问题！

**Comment by CinnabarCHU** [comment]
感谢issue及fix……我这就找个地方把自己埋了，当时加timeout时改了好几稿，结果最后pull错版本了……
