### ISSUE TITLE
[Bug]: 成功发送抢票请求后程序停止但库存不足

### ISSUE THREAD

**Issue by 3304552256** [mikumifa/biliTickerBuy#37]
### 部署方式

手动部署

### 系统环境

Windows11

### 异常情况

显示成功发送抢票请求，软件停止运行但返回错误代码100009库存不足

**Comment by mikumifa** [comment]
那就是因为商品库存不足

**Comment by 3304552256** [comment]
但是这样就直接停止程序了，必须要再点一下才能接着抢，能不能在它返回库存不足的时候继续抢票


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月17日(周三) 晚上8:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mikumifa/biliTickerBuy] [Bug]: 成功发送抢票请求后程序停止但库存不足 (Issue #37)




 
那就是因为商品库存不足
 
&mdash;

**Comment by mikumifa** [comment]
最新版已解决
