### ISSUE TITLE
[Bug]: 选择收货地址这一步卡住了

### ISSUE THREAD

**Issue by HOSHINOAQUAMARINE** [mikumifa/biliTickerBuy#39]
### 部署方式

手动部署

### 系统环境

w11

### 异常情况

![JP YN7D_@JJMZ}Y}9 8A{T5](https://github.com/mikumifa/biliTickerBuy/assets/135579143/2922a4b9-391d-4892-afae-6fc208f7dbf1)
点击提交无反应

**Comment by Kocurrrrrr** [comment]
+1

**Comment by mikumifa** [comment]
要有收货地址，随便填一个地址

**Comment by YanRuiMing** [comment]
> ### 部署方式
> 手动部署
> 
> ### 系统环境
> w11
> 
> ### Python环境
> _No response_
> 
> ### 异常情况
> ![JP YN7D_@JJMZ}Y}9 8A{T5](https://private-user-images.githubusercontent.com/135579143/323225651-2922a4b9-391d-4892-afae-6fc208f7dbf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjEzODksIm5iZiI6MTcxMzM2MTA4OSwicGF0aCI6Ii8xMzU1NzkxNDMvMzIzMjI1NjUxLTI5MjJhNGI5LTM5MWQtNDg5Mi1hZmFlLTZmYzIwOGY3ZGJmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMzM4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjA2MzhmMTAxMzI2MTU1ZTk0ODExYmQyYTI0MTY2ZDViNTA5NmI5NWVlYWM1NjNmMTFmZTU4MDhhZDYzNDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5453WYAUgqsBaHfNEj38Vj8Bj18Ixw7x7KHc_zZh9sY) 点击提交无反应
> 
> ### 报错信息
> _No response_

在我的-会员购-收货地址里面填上收货地址

**Comment by Kocurrrrrr** [comment]
解决了，谢谢

**Comment by HOSHINOAQUAMARINE** [comment]
解决了！谢谢
