### ISSUE TITLE
[Bug]: 打开就闪退

### ISSUE THREAD

**Issue by sq-dot** [mikumifa/biliTickerBuy#397]
### 部署方式

手动部署

### 版本

v2.8.6

### 异常情况

一打开显示出网址之后就闪退了

### 报错信息

![image](https://github.com/mikumifa/biliTickerBuy/assets/174876646/767d9897-16a2-412d-8314-1b53a24aa7e7)

**Comment by sq-dot** [comment]
对不起不要管我了，我忘记关梯子了对不起~~！！！！！！！！！！！

**Comment by WittF** [comment]
请关闭issues捏
