### ISSUE TITLE
求解，直接运行是这个结果

### ISSUE THREAD

**Issue by xianyu23333** [mikumifa/biliTickerBuy#4]
![6WZ)FLI9$% V8 S0QUWR`I6](https://user-images.githubusercontent.com/50168997/234556727-0791efd9-2e6b-4910-bd85-b35c8e5f28b9.png)

**Comment by mikumifa** [comment]
pip install -r requirements.txt

**Comment by xianyu23333** [comment]
> pip install -r requirements.txt

解决了，谢谢！
