### ISSUE TITLE
[Feature]: 关于抢票的功能添加

### ISSUE THREAD

**Issue by xunyoyo** [mikumifa/biliTickerBuy#404]
### 这是一个？

现有功能优化

### 详细描述

https://show.bilibili.com/platform/detail.html?id=88930
这种长时段放票的时候，脚本无法选择究竟是买哪一天的票。希望添加功能

**Comment by mikumifa** [comment]
有人要用吗，这个功能实现起来有点麻烦，而且好像很好抢这个
