### ISSUE TITLE
[Feature]: 大佬，可以支持选座位吗？

### ISSUE THREAD

**Issue by husbandfireslowly** [mikumifa/biliTickerBuy#41]
### 这是一个？

新功能

### 详细描述

想买的票需要选座位，这个怎么解决呢？会显示没有座位信息。

**Comment by mikumifa** [comment]
给个票id，下次更新时候加上

**Comment by husbandfireslowly** [comment]
84235😿> 给个票id，下次更新时候加上

**Comment by husbandfireslowly** [comment]
特别感谢🙏🏻试了一下不需要选座的场，特别迅速就锁座了（虽然我需要买的那个下午六点就要抢票，估计是用不上，不过还是大感谢🥹
