### ISSUE TITLE
[Bug]: 抢票成功没有声音提示

### ISSUE THREAD

**Issue by liuxing87** [mikumifa/biliTickerBuy#412]
### 部署方式

手动部署

### 版本

v2.8.7

### 异常情况

抢票设置了声音提示，但没有声音提示
![Uploading 屏幕截图 2024-08-25 165905.png…]()

**Comment by liuxing87** [comment]
![屏幕截图 2024-08-25 165905](https://github.com/user-attachments/assets/5557f5c8-6b28-4a20-827b-2f0bfdd44088)

**Comment by mikumifa** [comment]
确保路径是英文吧，中文没办法解析

**Comment by mikumifa** [comment]
https://stackoverflow.com/questions/58979872/why-do-i-have-utf-8-codec-cant-decode-byte-0xc4-in-position-0-invalid-conti
