### ISSUE TITLE
日历类的抢票日期无法选择

### ISSUE THREAD

**Issue by IggyMeraki** [mikumifa/biliTickerBuy#413]
### 这是一个？

现有功能优化

### 详细描述

https://show.bilibili.com/platform/detail.html?id=90962&from=pc_search
![image](https://github.com/user-attachments/assets/9d3e03aa-484e-4c0a-8113-01f60e8c8b31)

类似于这个链接中的日期较多，需要用到**日历**选择日期的情况下，输入程序后始终默认为第一天的信息，无法选择其他天，还烦请优化，感谢

**Comment by mikumifa** [comment]
这个功能还没实现

**Comment by mikumifa** [comment]
v2.8.8 添加这个功能
