### ISSUE TITLE
[Bug]: 抢票时无法下单，显示票价发生变化。

### ISSUE THREAD

**Issue by xtdp123** [mikumifa/biliTickerBuy#414]
### 部署方式

release的打包文件

### 版本

2.8.7和2.8.6都试了

### 异常情况

https://show.bilibili.com/platform/detail.html?id=91117&from=pc_order_detail  抢该活动时出现的情况，是因为购票页面显示658元，但实际上的下单支付页面是668元导致的？

**Comment by xtdp123** [comment]
![DJF}8IYXEPC{QC91C5DT356](https://github.com/user-attachments/assets/b24fabf5-4e7e-4305-895e-6100672143cf)

**Comment by mikumifa** [comment]
v2.8.8 修复这个问题

**Comment by HYCF765** [comment]
乐，一样的场景，一样的问题
