### ISSUE TITLE
[Bug]: 抢票失败 创建订单无反应

### ISSUE THREAD

**Issue by Allroha** [mikumifa/biliTickerBuy#423]
### 部署方式

release的打包文件

### 版本

2.8.9 patch.1

### 异常情况

今早抢[CICF](https://show.bilibili.com/platform/detail.html?id=91171)没抢到 log如下 是B站改东西了吗 试了下别的[小漫展](https://show.bilibili.com/platform/detail.html?id=89569)也不能创建订单
![2024-09-15_10-11-46](https://github.com/user-attachments/assets/717259d3-c4a8-49d5-99b6-774f04b2198a)

同时 项目在开票前后的名字貌似也会影响到抢票执行
![photo_2024-09-15_10-22-10](https://github.com/user-attachments/assets/64b097e8-5a50-4b17-a2c9-0d67b980d322)

### 报错信息

[log.txt](https://github.com/user-attachments/files/17004407/log.txt)

**Comment by mikumifa** [comment]
b站接口有地方改了一点，导致计算出错了

**Comment by mikumifa** [comment]
等v2.8.9-patch.2

**Comment by Allroha** [comment]
> b站接口有地方改了一点，导致计算出错了

门票名称中的售卖状态“暂时售罄”和“预售中”会影响下单请求吗

**Comment by mikumifa** [comment]
> > b站接口有地方改了一点，导致计算出错了
> 
> 门票名称中的售卖状态“暂时售罄”和“预售中”会影响下单请求吗

这个要看票去自己判断了，程序不管这些能不能抢，只要你让他抢他就会发请求
