### ISSUE TITLE
[Feature]: 关于保持登录状态

### ISSUE THREAD

**Issue by HsuJv** [mikumifa/biliTickerBuy#424]
### 这是一个？

现有功能优化

### 详细描述

曾经的版本里是有保存cookie在资源文件里实现重复打开程序自动加载的功能。现在的AIO版本似乎没法保存cookie，能否增加一个启动参数指定cookies.json并且默认值设置为
```python
os.path.join(os.getcwd(), 'cookies.json')
```

**Comment by mikumifa** [comment]
打包成单文件导致出错了
