### ISSUE TITLE
[Bug]: 信息完善的情况下仍然无法生成配置文件

### ISSUE THREAD

**Issue by Allroha** [mikumifa/biliTickerBuy#426]
### 部署方式

release的打包文件

### 版本

2.8.9 Patch.3

### 异常情况

登录第一个号的时候可以正常获取并生成配置文件
但是导入第二个号后再次获取就会提示“生成错误，仔细看看你可能有哪里漏填的”
重启程序才可以继续获取

**Comment by mikumifa** [comment]
我到时候复现一下

**Comment by mikumifa** [comment]
没有复现成功，切换账号时候重新登陆一下比较好
