### ISSUE TITLE
[Feature]: 抢票频率更改

### ISSUE THREAD

**Issue by wy3057** [mikumifa/biliTickerBuy#43]
### 这是一个？

新功能

### 详细描述

可以给一个时间设置吗
就是抢票的频次自定义，比如说0.5秒抢一次或者1秒抢一次，从源码改比较麻烦（狗头保命）
感觉0.5秒以上应该都不会封
还有作者开个赞助
![e6c79b2ee23ae596ff69cb692a889ff4](https://github.com/mikumifa/biliTickerBuy/assets/87601913/0a632560-1a06-43fa-8906-9e4891ef81e0)
看不惯这人，我不愿意打钱给他

**Comment by mikumifa** [comment]
我不是太缺钱，这边正在改

**Comment by mikumifa** [comment]
最新版加了

**Comment by sebelhot** [comment]
> 最新版加了

大佬有没有试过可能的最小频率，调的特别低的话是可能会被封嘛

**Comment by mikumifa** [comment]
1s是没事的

**Comment by mikumifa** [comment]
准时抢票的话主要发一次就行了，
蹲票的话1s应该没问题
