### ISSUE TITLE
[Bug]: 抢票地址生成配置位置一致显示connection error out，后面导入登入文件也是error out

### ISSUE THREAD

**Issue by lava-none** [mikumifa/biliTickerBuy#430]
### 部署方式

手动部署

### 版本

v2.8.9-patch.3

### 异常情况

v2.8.9-patch.3 抢票地址生成配置位置一致显示connection error out，后面导入登入文件也是error out

### 报错信息

connection error out

**Comment by mikumifa** [comment]
重启 and 关梯子
