### ISSUE TITLE
[Bug]: 提示账号异常

### ISSUE THREAD

**Issue by wlwxj** [mikumifa/biliTickerBuy#440]
### 部署方式

release的打包文件

### 版本

0.0.2

### 异常情况

请求体: {'code': 100041, 'errno': 100041, 'errtag': 0, 'msg': '您的账号存在异常，暂时无法购票', 'data': {}}
![image](https://github.com/user-attachments/assets/a5928b34-f511-43a4-abe4-013b5153e12b)

**Comment by JinjaNatsume** [comment]
> ### 部署方式
> release的打包文件
> 
> ### 版本
> 0.0.2
> 
> ### 异常情况
> 请求体: {'code': 100041, 'errno': 100041, 'errtag': 0, 'msg': '您的账号存在异常，暂时无法购票', 'data': {}} ![image](https://private-user-images.githubusercontent.com/87691511/371887568-a5928b34-f511-43a4-abe4-013b5153e12b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NTAyNzYsIm5iZiI6MTcyNzY0OTk3NiwicGF0aCI6Ii84NzY5MTUxMS8zNzE4ODc1NjgtYTU5MjhiMzQtZjUxMS00M2E0LWFiZTQtMDEzYjUxNTNlMTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDIyNDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNTcyZTE0OTUxMzRhMWFhNzA4ZDZhMmVjMWJlZDcwYWE2YTA3Y2M3ZDg0NjJlZTUwODA4ZTRlMTAzNmM4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P81-ap1_--R1RodVW8Nb87ioNLZoBM8TDvqfhZCFu3A)
> 
> ### 报错信息
> _No response_

看着像号被ban了

**Comment by 131A3D7** [comment]
吃叔叔的风控了

**Comment by wlwxj** [comment]
换三个号了都一样😭😭跟ip有关吗

**Comment by mikumifa** [comment]
有一说一，你确定你用的是b站的cookie？

**Comment by mikumifa** [comment]
cpp和b站的所有配置都是不互通的

**Comment by mikumifa** [comment]
2个是完全不一样的程序

**Comment by kitzza** [comment]
解决了吗
