### ISSUE TITLE
[Bug]: 大佬，启动后只有终端界面，没有图形界面

### ISSUE THREAD

**Issue by sebelhot** [mikumifa/biliTickerBuy#47]
### 部署方式

手动部署

### 系统环境

windows11

### Python环境

python3.11

### 异常情况

![image](https://github.com/mikumifa/biliTickerBuy/assets/162395969/b30ad312-37cb-460a-a3ab-476b80503378)
只有这个界面，没有图形界面捏

### 报错信息

如果是因为我不会操作的原因而误报在此致歉

**Comment by jack68CN** [comment]
同问，还没找到问题

**Comment by mikumifa** [comment]
启动终端第一行会显示

Running on local URL:  http://127.0.0.1:xxx
访问对应的网址即可

**Comment by sebelhot** [comment]
> 启动终端第一行会显示
> 
> Running on local URL: http://127.0.0.1:xxx 访问对应的网址即可
懂了 感谢
