### ISSUE TITLE
[Bug]: 输入ID后报错

### ISSUE THREAD

**Issue by YokeLYun** [mikumifa/biliTickerBuy#48]
### 部署方式

手动部署

### 系统环境

windows11

### 异常情况

进http://127.0.0.1:7860网页之后输入ID报错

### 报错信息

Message: Selenium Manager failed for: D:\1\main\_internal\selenium\webdriver\common\windows\selenium-manager.exe --browser MicrosoftEdge --output json.
error sending request for url (https://msedgedriver.azureedge.net/LATEST_RELEASE_123_WINDOWS): error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)

**Comment by mikumifa** [comment]
看一下 这个#31

**Comment by YokeLYun** [comment]
佬，浏览器版本2478这里面没有对应的怎么办

**Comment by YokeLYun** [comment]
> 看一下 这个#31

佬，浏览器版本2478这里面没有对应的怎么办
