### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by BlogliazZ** [mikumifa/biliTickerBuy#49]
### 这是一个？

新功能

### 详细描述

![Screenshot_2024-04-22-18-48-25-541_tv danmaku bili](https://github.com/mikumifa/biliTickerBuy/assets/167755899/70f28f85-0585-4aef-9fe6-65c4b27fd049)
b站抢票图灵文字认证能不能解决一下

**Comment by mikumifa** [comment]
已经解决了

**Comment by BlogliazZ** [comment]
好的，谢谢大佬

**Comment by BlogliazZ** [comment]
![1713830137673](https://github.com/mikumifa/biliTickerBuy/assets/167755899/1acb6c04-caa0-48fe-8b02-a304f0308742)
![1713830137679](https://github.com/mikumifa/biliTickerBuy/assets/167755899/19509362-fa98-46d7-a4cc-938937399ee0)
这个会不会影响到点抢票？关于显示无法购买问题

**Comment by BlogliazZ** [comment]
@mikumifa

**Comment by mikumifa** [comment]
你现在还有这个问题吗

**Comment by mikumifa** [comment]
我没遇到这个情况，不知道为什么你的账号挂了，是不是没有登录过
