### ISSUE TITLE
大佬这怎么办TvT

### ISSUE THREAD

**Issue by xwq2007** [mikumifa/biliTickerBuy#5]
![SM}FKX5%{@ `SXWV~)W9QHW](https://user-images.githubusercontent.com/131879802/234577472-7725bd8d-6cc6-4e65-8c34-8693624d5b45.png)

**Comment by mikumifa** [comment]
你看看当前目录有没有这个文件

**Comment by xwq2007** [comment]
![XP0{8R%7KXZ~WIMH5GT1{9Q](https://user-images.githubusercontent.com/131879802/234578537-29cca902-8f8c-49a8-9eff-af267a9df9f6.png)
这里吗

**Comment by xwq2007** [comment]
是哪个Scripts吗

**Comment by xwq2007** [comment]
有的呀

**Comment by mikumifa** [comment]
截个图

**Comment by xwq2007** [comment]
![XP0{8R%7KXZ~WIMH5GT1{9Q](https://user-images.githubusercontent.com/131879802/234580181-7ab8cef7-5348-426c-8b41-3e4b19f16bbe.png)

**Comment by mikumifa** [comment]
不是这个地方 😢 ,你先找到我的main.py文件,在那个目录

**Comment by xwq2007** [comment]
但还是会出现ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by mikumifa** [comment]
在那个文件夹打开命令行

**Comment by xwq2007** [comment]
打开之后要干嘛啊

**Comment by xwq2007** [comment]
啊算了还是不弄了我这脑子太笨了完全不会操作
