### ISSUE TITLE
[Bug]: 点击提交票id无反应

### ISSUE THREAD

**Issue by Ark-Schwarz** [mikumifa/biliTickerBuy#52]
### 部署方式

release的打包文件

### 系统环境

Windows11

### Python环境

Python 3.10

### 异常情况

点击后无任何响应
<img width="1280" alt="image" src="https://github.com/mikumifa/biliTickerBuy/assets/46624134/b8410a03-5a0d-4923-8f1c-cfdc16413af8">
<img width="730" alt="image" src="https://github.com/mikumifa/biliTickerBuy/assets/46624134/f7f2f416-9be7-489b-90ea-6f052aa2be04">

**Comment by mikumifa** [comment]
多点几下
