### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lllLllori** [mikumifa/biliTickerBuy#53]
### 部署方式

手动部署

### 系统环境

windows10

### 异常情况

问问怎么提前设置抢还没有开售的票

### 报错信息

![image](https://github.com/mikumifa/biliTickerBuy/assets/101250945/519c8975-03f7-4f48-867a-8b636b1c90c3)我选择了抢票时间后点击开始抢票会显示这个
![image](https://github.com/mikumifa/biliTickerBuy/assets/101250945/7591aa0d-9d71-4cfe-a594-e2564eccefca)

**Comment by mikumifa** [comment]
开售的票是没办法抢的，这个抢票脚本的作用就是准时去抢刚发售的票，而不是在发售前去抢票

**Comment by lllLllori** [comment]
也就是我需要准点自己手动点击开始抢票吗？那我没太明白设计抢票时间的意义0.0

**Comment by mikumifa** [comment]
我刚刚测试一下，不知道是不是明日方舟的接口变了，现在访问order/prepare接口会显示账号异常，不过程序会一直重试去访问创建订单

**Comment by mikumifa** [comment]
过一会改一下，这确定是个问题，抢票会请求2个接口，应该是订单准备，应该是发送订单，我时间等待实在第二个接口，等等改成第一个

**Comment by lllLllori** [comment]
我测试了下崩铁的也是一样报这个错误，其他的演出倒是可以正常生成二维码

**Comment by mikumifa** [comment]
等一下 v2.4.1版本，实际上程序没有错，就是对没有发售的票抢会这样

**Comment by lllLllori** [comment]
好的 谢谢 那我到时候准点测试一下
