### ISSUE TITLE
[Feature]: 您的账号存在异常，暂时无法购票

### ISSUE THREAD

**Issue by 893597175** [mikumifa/biliTickerBuy#54]
### 这是一个？

现有功能优化

### 详细描述

![Screenshot_2024-04-23-15-52-22-493_youqu android todesk-edit](https://github.com/mikumifa/biliTickerBuy/assets/167855121/d59a1c79-828b-40d7-b16a-92f9c11448de)
请问这怎么解决

**Comment by mikumifa** [comment]
快修了，等一会

**Comment by mikumifa** [comment]
等一下 v2.4.1版本，实际上程序没有错，就是对没有发售的票抢会这样

**Comment by 893597175** [comment]
> 等一下 v2.4.1版本，实际上程序没有错，就是对没有发售的票抢会这样

好的好的
