### ISSUE TITLE
2024/4/23 明日方舟实测可行

### ISSUE THREAD

**Issue by mikumifa** [mikumifa/biliTickerBuy#55]
![qq_pic_merged_1713870462304](https://github.com/mikumifa/biliTickerBuy/assets/99951454/994462fe-793e-469a-b1da-b30903f32647)

**Comment by mikumifa** [comment]
20秒容错![image](https://github.com/mikumifa/biliTickerBuy/assets/99951454/8f4b9a51-be90-48ec-9dfd-d611c1a8382d)

**Comment by Glorysmith233** [comment]
我这显示抢票成功 为什么待付款里没有呢？？

**Comment by mikumifa** [comment]
可能有延迟吧，反正我抢到之后就跳二维码了

**Comment by JasenHp** [comment]
博主，这个是啥子问题呀

**Comment by JasenHp** [comment]
![error](https://github.com/mikumifa/biliTickerBuy/assets/167872262/5ace4880-396f-4a43-a7b9-60cca78f911c)
博主 这个是什么问题呀

**Comment by BaSllfgy** [comment]
显示成功，但是没有待付款

**Comment by keleus** [comment]
你下单的时候需要填验证码么？

**Comment by JasenHp** [comment]
> ![error](https://private-user-images.githubusercontent.com/167872262/324810540-5ace4880-396f-4a43-a7b9-60cca78f911c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzIxNTgsIm5iZiI6MTcxMzg3MTg1OCwicGF0aCI6Ii8xNjc4NzIyNjIvMzI0ODEwNTQwLTVhY2U0ODgwLTM5NmYtNGE0My1hN2I5LTYwY2NhNzhmOTExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMTMwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTZkNjVkN2JmMGY2ZDdkNzA0Yjc2NDVjNTMwM2U0ZjY5MWVmZTZkOGFkZjY3Mjg1Y2QxYTliMzgxYTU0M2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uVn-lTw0zikYTQpbgeRXyQr995F7BMhVFus6heB3WhE) 博主 这个是什么问题呀 网站上面应该会提示你下载浏览器驱动的， 具体可以看 #31

是不是因为没有下载Selenium插件？

**Comment by Congrooo** [comment]
INFO:root:list indices must be integers or slices, not NoneType  是什么情况

**Comment by WittF** [comment]
😎👍

**Comment by mikumifa** [comment]
> 我也抢到了同一天的，到时候去现场不知道能不能捕捉到mikumifa大佬。

我不去 🙂 , 抢这个就是测试一下脚本的，目前看来没问题

**Comment by mikumifa** [comment]
> INFO:root:list indices must be integers or slices, not NoneType 是什么情况

要结合上下文吧，目前没办法把保存情况全考虑到， 所以奇怪的报错都要结合程序来分析

**Comment by mikumifa** [comment]
> > ![error](https://private-user-images.githubusercontent.com/167872262/324810540-5ace4880-396f-4a43-a7b9-60cca78f911c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzIxNTgsIm5iZiI6MTcxMzg3MTg1OCwicGF0aCI6Ii8xNjc4NzIyNjIvMzI0ODEwNTQwLTVhY2U0ODgwLTM5NmYtNGE0My1hN2I5LTYwY2NhNzhmOTExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMTMwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTZkNjVkN2JmMGY2ZDdkNzA0Yjc2NDVjNTMwM2U0ZjY5MWVmZTZkOGFkZjY3Mjg1Y2QxYTliMzgxYTU0M2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uVn-lTw0zikYTQpbgeRXyQr995F7BMhVFus6heB3WhE) 博主 这个是什么问题呀 网站上面应该会提示你下载浏览器驱动的， 具体可以看 #31
> 
> 是不是因为没有下载Selenium插件？

是的

**Comment by Congrooo** [comment]
会因为扫码不及时而没抢到吗

**Comment by mikumifa** [comment]
> 会因为扫码不及时而没抢到吗

出扫码，说明已经下单了，十分钟之后退单

**Comment by JasenHp** [comment]
> > > ![error](https://private-user-images.githubusercontent.com/167872262/324810540-5ace4880-396f-4a43-a7b9-60cca78f911c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzIxNTgsIm5iZiI6MTcxMzg3MTg1OCwicGF0aCI6Ii8xNjc4NzIyNjIvMzI0ODEwNTQwLTVhY2U0ODgwLTM5NmYtNGE0My1hN2I5LTYwY2NhNzhmOTExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMTMwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTZkNjVkN2JmMGY2ZDdkNzA0Yjc2NDVjNTMwM2U0ZjY5MWVmZTZkOGFkZjY3Mjg1Y2QxYTliMzgxYTU0M2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uVn-lTw0zikYTQpbgeRXyQr995F7BMhVFus6heB3WhE) 博主 这个是什么问题呀 网站上面应该会提示你下载浏览器驱动的， 具体可以看 #31
> > 
> > 
> > 是不是因为没有下载Selenium插件？
> 
> 是的

解决了 尝试成功 非常感谢！

**Comment by uselessFUSE** [comment]
@mikumifa 大佬，我是小白，想问一下edge124.0.2478.51版本能用吗？

**Comment by WittF** [comment]
> @mikumifa 大佬，我是小白，想问一下edge124.0.2478.51版本能用吗？

我可以
![image](https://github.com/mikumifa/biliTickerBuy/assets/108567138/d4d97ec6-24a5-4dfe-8a01-687f5b5f1f49)

**Comment by uselessFUSE** [comment]
@WittF 但是我前段时间能正常使用，今天测了一下就是一直在闪退

**Comment by WittF** [comment]
> @WittF 但是我前段时间能正常使用，今天测了一下就是一直在闪退

换路径或重新下载试试

**Comment by uselessFUSE** [comment]
@WittF 请问一下大佬，用的是哪个版本的驱动？我重新下载后还是报错：“ error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)”

**Comment by mikumifa** [comment]
> 诶对了是在19：00之前就选好要买的票以及信息，然后19：00整就点击开始抢票吗？ （顺便问一下抢票间隔多少合适）

有人测试是500ms

**Comment by mikumifa** [comment]
> @WittF 请问一下大佬，用的是哪个版本的驱动？我重新下载后还是报错：“ error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)”

我默认就有，经验之谈就是下最新版的浏览器和最新版的驱动就没问题，（）什么都去官网下载

**Comment by WittF** [comment]
> @WittF 请问一下大佬，用的是哪个版本的驱动？我重新下载后还是报错：“ error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)”

我也出现过启动一段时间后就自动关闭, 也是有弹提示远程主机强迫关闭了一个现有的连接, 但是没怎么仔细看, 重新解压后过了一会儿就正常了

**Comment by WittF** [comment]
> 诶对了是在19：00之前就选好要买的票以及信息，然后19：00整就点击开始抢票吗？ （顺便问一下抢票间隔多少合适）

可以提早配置好选择抢票时间, 时间到了就会开始抢票, 但是可能需要手动过验证, 记得要检查一下

**Comment by uselessFUSE** [comment]
@WittF @mikumifa 大佬，我重启后依旧闪退，浏览器和驱动和原来一样，最近配置变动就是换了个网络。

**Comment by WittF** [comment]
> @WittF @mikumifa 大佬，我重启后依旧闪退，浏览器和驱动和原来一样，最近配置变动就是换了个网络。

远程主机强制关闭连接通常不是浏览器的问题

**Comment by xiangwandamowan** [comment]
![QQ截图20240423224754](https://github.com/mikumifa/biliTickerBuy/assets/167890104/bbd87550-fe97-402a-8db5-555432bdf5c8)
想着搞搞回流票来着。但回流票的时候验证没用了

**Comment by xiangwandamowan** [comment]
![Uploading QQ截图20240423224650.png…]()

**Comment by uselessFUSE** [comment]
@mikumifa 
![1](https://github.com/mikumifa/biliTickerBuy/assets/167861573/47da86ee-307d-4ca7-b533-9a53c95a2e2b)
大佬有空能看一下我这是因为啥吗？驱动重装过，网络代理也测过好像都不行

**Comment by WittF** [comment]
> ![QQ截图20240423224754](https://private-user-images.githubusercontent.com/167890104/324881122-bbd87550-fe97-402a-8db5-555432bdf5c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODU0OTksIm5iZiI6MTcxMzg4NTE5OSwicGF0aCI6Ii8xNjc4OTAxMDQvMzI0ODgxMTIyLWJiZDg3NTUwLWZlOTctNDAyYS04ZGI1LTU1NTQzMmJkZjVjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxNTEzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTMwYmVjYjVkMDQyY2JmOTFlZTJhMTE2YWU1NmNlNjI2MTM4ZGFhODdiYjQ1MTE0ZjI1MGI0NzVhOGYxMDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1NnfGV_w4RpFPWeqq8Ei4757N0KwfcC-R5iKLx8XbA0) 想着搞搞回流票来着。但回流票的时候验证没用了

配置信息不是加密的, 小心泄露个人隐私了

**Comment by mikumifa** [comment]
> @WittF @mikumifa 大佬，我重启后依旧闪退，浏览器和驱动和原来一样，最近配置变动就是换了个网络。

参考下这个吧https://github.com/mikumifa/biliTickerBuy/wiki/%E6%B5%8F%E8%A7%88%E5%99%A8%E9%A9%B1%E5%8A%A8%E5%AE%89%E8%A3%85%E5%87%BA%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E5%BC%8F

**Comment by xiangwandamowan** [comment]
> > ![QQ截图20240423224754](https://private-user-images.githubusercontent.com/167890104/324881122-bbd87550-fe97-402a-8db5-555432bdf5c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODUxMjIsIm5iZiI6MTcxMzg4NDgyMiwicGF0aCI6Ii8xNjc4OTAxMDQvMzI0ODgxMTIyLWJiZDg3NTUwLWZlOTctNDAyYS04ZGI1LTU1NTQzMmJkZjVjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxNTA3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzU5OTk0ZTcyNTM5ODcxNDM2ZmIwZTcwMjViY2NlYjZkNjk2ZDZkNjQ0ODEzMDM5NzQwMmFmOTgwYzU0YjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5knClcq6HxobsHaI8ni3FWXt8Oxp2tyADZwXeBRhe5g) 想着搞搞回流票来着。但回流票的时候验证没用了
> 
> 验证完成之后还要点一下第二个按钮，点了吗

点了，说极验gee test 验证失败
只能手动用手机过验证

**Comment by uselessFUSE** [comment]
@mikumifa 应用问题无法解决，但是我直接运行main代码能正常使用了

**Comment by JYK89** [comment]
我也试了下 抢3号回流票成功了一次

**Comment by jwj1342** [comment]
牛逼，成功了，感谢作者，怎么不放打赏二维码

**Comment by mikumifa** [comment]
> 牛逼，成功了，感谢作者，怎么不放打赏二维码

用爱发电

**Comment by Lrrrrrrt** [comment]
![1716728446404](https://github.com/mikumifa/biliTickerBuy/assets/108092864/9634f2a7-e134-4a0e-b25c-e0deeb1714cf)
这种是咋回事呀，下单提示慢一点
![1716728446404](https://github.com/mikumifa/biliTickerBuy/assets/108092864/44ad2eba-25ed-486b-996e-98c561249ae4)
跪求  软件是不是不能用了啊
