### ISSUE TITLE
[Bug]: 刷新前后选择其他票生成票属性值不变

### ISSUE THREAD

**Issue by Ark-Schwarz** [mikumifa/biliTickerBuy#57]
### 部署方式

release的打包文件

### 系统环境

Windows11

### 异常情况

[app.log](https://github.com/mikumifa/biliTickerBuy/files/15076759/app.log)
<img width="1280" alt="屏幕截图 2024-04-23 202020" src="https://github.com/mikumifa/biliTickerBuy/assets/46624134/d1c8a399-53e6-4ccf-8105-123944b05f99">
<img width="1045" alt="屏幕截图 2024-04-23 202116" src="https://github.com/mikumifa/biliTickerBuy/assets/46624134/68b33c1c-13c3-4b0d-b9d0-4dcbc01c9988">

**Comment by mikumifa** [comment]
没太看懂，具体啥问题

**Comment by Ark-Schwarz** [comment]
就是填入其他票id后生成，依旧是原来那一个，并没有重新生成

**Comment by mikumifa** [comment]
现在先重新打开程序生成，我后面修改

**Comment by Ark-Schwarz** [comment]
ok，那这个可以关了

**Comment by mikumifa** [comment]
修完关，现在不急
