### ISSUE TITLE
错误码:100041 错误码解析: 未知错误码[Bug]: 

### ISSUE THREAD

**Issue by yydsch4** [mikumifa/biliTickerBuy#59]
### 部署方式

手动部署

### 系统环境

windows10

### 异常情况

错误码:100041 错误码解析: 未知错误码，这是什么

**Comment by mikumifa** [comment]
正常不会这样的，你抢的票可能不存在，或者请求太多了，也就是违规的请求太多了，同时确保你使用的是v2.4.2以后得版本

**Comment by mikumifa** [comment]
参考#56， 抢票前违规请求过多会在抢票时候被风控，可以拿普通票练手，然后要提前熟悉一下验证码
