### ISSUE TITLE
这真的能抢到吗为什么我自己写的requests脚本都刷不到票😭

### ISSUE THREAD

**Issue by lchypwx** [mikumifa/biliTickerBuy#6]

**Comment by mikumifa** [comment]
我目前没成功

**Comment by yuban1120** [comment]
我记得推掉的票的会和第二波发售的票一起放出来，现在好像根本就没票

**Comment by ChisatoNishikigi73** [comment]
会卡在下一步支付，我进去过几次，这次我加了些东西，看能不能直接跳到付款

**Comment by ChisatoNishikigi73** [comment]
> 有,会偶尔有票,具体原因不知道

官方炒作+退票maybe

**Comment by 2020015082** [comment]
怎样选择买两张票啊，代码里有设置吗

**Comment by xianyu23333** [comment]
> 会卡在下一步支付，我进去过几次，这次我加了些东西，看能不能直接跳到付款

大佬写出来可以分享一下吗？

**Comment by Chaos4869** [comment]
大佬这个具体咋设置啊想抢第二轮但不会设置，现在运行文件一打开就闪退

**Comment by xmbhjQAQ** [comment]
> 大佬这个具体咋设置啊想抢第二轮但不会设置，现在运行文件一打开就闪退

Python正常安装并加入path的情况下
库里面应该有一个requirement.txt
pip intsall -r  requirement.txt
安装依赖
然后去下载你对应浏览器的Driver，放到py根目录Script里
（具体下载地址和下载后操作我库里面应该有一个我fork项目的介绍文件里面有具体下载地址，原项目已经删库了）

不出意外的话项目应该就可以正常启动了

**Comment by mikumifa** [comment]
不太建议用这个来抢第二轮,这个适合蹲票,抢票的话, 网站崩的话没办法使用
