### ISSUE TITLE
[Bug]: 对未发售进行抢票，后台显示抢票异常

### ISSUE THREAD

**Issue by bugflowalltime** [mikumifa/biliTickerBuy#61]
### 部署方式

release的打包文件

### 系统环境

Windows10

### 异常情况

2.4.2版本，票还没发售，后台显示两个报错，一个是未发售一个是账号存在异常，请问这种是正常的吗，还是需要发售时再换个账号

### 报错信息

![35CD942A45B4F98F99E648E05F3725E2](https://github.com/mikumifa/biliTickerBuy/assets/167968901/80152e4c-9cbd-422d-8ed6-2296b52488be)

**Comment by mikumifa** [comment]
看看这个#59
