### ISSUE TITLE
2024/4/24 星穹铁道实测可行

### ISSUE THREAD

**Issue by mikumifa** [mikumifa/biliTickerBuy#62]
17秒容错

![image](https://github.com/mikumifa/biliTickerBuy/assets/99951454/8aec5990-2ae7-43ec-8bab-9680e2b28c90)

**Comment by HenveKim** [comment]
感谢大佬
![image](https://github.com/mikumifa/biliTickerBuy/assets/139193803/d02fd0f7-2ce4-4d54-bb9f-b240242f358b)

**Comment by Kocurrrrrr** [comment]
佬，显示“错误, 错误码:0 错误码解析: 未知错误码” 是什么原因

**Comment by mikumifa** [comment]
> 佬，显示“错误, 错误码:0 错误码解析: 未知错误码” 是什么原因

看控制台分析，或者给个log日志文件

**Comment by QiyueShinobu** [comment]
未知错误码好像都是 INFO:root:An error occurred in file 'C:\Users\Administrator\Desktop\main\_internal\main.py' at line 219: 429 Client Error: Too Many Requests for url

**Comment by Kocurrrrrr** [comment]
INFO:root:An error occurred in file 'D:\bilibili-buy\main\_internal\main.py' at line 219: 429 Client Error: Too Many Requests for url: https://show.bilibili.com/api/ticket/order/createV2?project_id=84096
INFO:root:错误码:0 错误码解析: 未知错误码, 请求体: {'errno': 0, 'errtag': 0, 'msg': '', 'data': {'project_id': 84096, 'project_name': '上海·「星铁LAND」2024星穹铁道嘉年华', 'project_img': '//i1.hdslb.com/bfs/openplatform/202404/CW93VZON1712826642232.jpeg', 'order_type': 1, 'buyer_info': '2,1', 'express_fee': 0, 'express_type': 0, 'venue_name': '上海国家会展中心', 'screen_id': 171743, 'screen_name': '2024-05-04 周六', 'ticket_type': 2, 'deliver_type': 1, 'count': 1, 'item_total_money': 25800, 'pay_money': 25800, 'couponList': [], 'year_card': {'can_use': 0}, 'need_contact': 0, 'id_bind': 2, 'ticket_info': {'sku_id': 483804, 'name': '普通票', 'price': 25800, 'count': 1, 'link_sc_name': [], 'is_package': 0, 'package_num': 1}, 'enter_notice': '入场时请配合现场指导，如有防疫要求，请严格遵守', 'show_cashier': False, 'purchase_agreement': True, 'contact_info': None}},剩余次数: 无限

**Comment by mikumifa** [comment]
感觉就是b站服务器撑不住那一秒 了

**Comment by mikumifa** [comment]
拿定时抢的话，基本上能在前几秒就把请求发了，前几秒时间没把握住的话，后面就开始拥挤了，那时候脚本优势已经没有了

**Comment by vovoRRR** [comment]
问一下这个脚本是否可以捡漏票，就抢到一天的

**Comment by mikumifa** [comment]
> 问一下这个脚本是否可以捡漏票，就抢到一天的

自己设置参数吧，把这个软件理解成一个帮助发送请求的工具，至于怎么发，靠自己配置

**Comment by Congrooo** [comment]
抢到了，谢谢！！！！！！

**Comment by vovoRRR** [comment]
<img width="858" alt="f5d516a07653a8bc0fe34c116b9c6b9b" src="https://github.com/mikumifa/biliTickerBuy/assets/167942772/83b4f027-bed2-43a3-8208-3de6a269c0b9">
验证失败怎么解决

**Comment by vovoRRR** [comment]
重新开了几次就好了，之前几次一直在要验证

**Comment by mikumifa** [comment]
> 重新开了几次就好了，之前几次一直在要验证

没遇见过，重开的话，可能操作有误，重新开的话，不能刷新，要软件关了重新打开

**Comment by vovoRRR** [comment]
INFO:root:prepare header: {'Date': 'Wed, 24 Apr 2024 12:33:19 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '221', 'Connection': 'keep-alive', 'Server': 'nginx', 'Trace-Id': '3382483082', 'Expires': 'Wed, 24 Apr 2024 12:33:18 GMT', 'Cache-Control': 'no-cache', 'X-Cache-Webcdn': 'BYPASS from blzone06'}
INFO:root:prepare: {'code': 0, 'errno': 0, 'errtag': 0, 'msg': '', 'data': {'ga_data': {'decisions': [], 'risk_level': 1, 'grisk_id': '19d6eaf7cdaaa9b630c6089dce6628fc', 'open': 0, 'riskParams': []}, 'shield': {'open': 0}, 'token': 'wGYo_A8AAUiAAAKe3gEAAQAHYjM.'}}

**Comment by vovoRRR** [comment]
问一下这个问题

**Comment by mikumifa** [comment]
> 问一下这个问题

你这个看日志没用，会跑源代码吗

**Comment by vovoRRR** [comment]
欧了，朋友一起抢到了，订单在他那边，不能重复下的报错

**Comment by JasenHp** [comment]
我也抢到了5.4 感谢大佬

**Comment by delaube1** [comment]
佬这个怎么切换b站账号啊？我同行的朋友没抢到我想帮他们抢一下，应该改哪个配置文件

**Comment by JasenHp** [comment]
> 佬这个怎么切换b站账号啊？我同行的朋友没抢到我想帮他们抢一下，应该改哪个配置文件

请教+1

**Comment by 781572496** [comment]
> > 佬这个怎么切换b站账号啊？我同行的朋友没抢到我想帮他们抢一下，应该改哪个配置文件
> 
> 请教+1

B站能直接添加购买人信息，用你的号帮朋友抢。一定想换账号的话，可以试试删掉软件，然后重新解压一份出来，还不行的话试试用旧的版本把账号挤下来或者直接用旧版本抢（没试过，不保证可行）。

**Comment by delaube1** [comment]
看明白了，改缓存就好了，谢谢佬
