### ISSUE TITLE
[Bug]: 购买多人票会报错：请选择1位购买人

### ISSUE THREAD

**Issue by Sh12uku** [mikumifa/biliTickerBuy#64]
### 部署方式

release的打包文件

### 系统环境

Windows11

### 异常情况

购买票数超过一个的话会提示：请选择1位购买人

### 报错信息

状态码: 209001(未知错误码), 请求体: {'errno': 209001, 'errtag': 0, 'msg': '请选择1位购买人', 'data': {}} 剩余次数: 无限

**Comment by mikumifa** [comment]
估计是你票填错了
