### ISSUE TITLE
如何更改会员购账号

### ISSUE THREAD

**Issue by ghost** [mikumifa/biliTickerBuy#65]
### 这是一个？

新功能

### 详细描述

如何更改会员购账号

**Comment by mikumifa** [comment]
暂时先删软件重新来

**Comment by mikumifa** [comment]
想了一下，这个功能就不实现，需要多个账户的，可以多开几个APP，这样可以杜绝，使用B账号抢票但是却是A账号配置文件从而产生的情况，太自由反而不太好
