### ISSUE TITLE
[Bug]: 在运行一段时间后不能继续抢票

### ISSUE THREAD

**Issue by yydsch4** [mikumifa/biliTickerBuy#66]
### 部署方式

手动部署

### 系统环境

windows10

### 异常情况

在运行一段时间后不能继续抢票，暂停并且重新开始抢票也开始不了，为什么

**Comment by mikumifa** [comment]
贴log，

**Comment by mikumifa** [comment]
exe同目录

**Comment by yydsch4** [comment]
好的，谢谢，很感谢你的软件，我电脑上抢到了，在帮同学看看有没有回流票，希望吧

**Comment by mikumifa** [comment]
好的，目前程序可能有bug，exe文件关了重开基本上能解决一大半事情
