### ISSUE TITLE
[Bug]: 填入数字ID后报错

### ISSUE THREAD

**Issue by YokeLYun** [mikumifa/biliTickerBuy#69]
### 部署方式

手动部署

### 版本

v2.5.4

### 异常情况

用editthiscookie导出coookies后成功运行，但在网页填ID又报错了
（私密马赛，我的问题太多了TT）

### 报错信息

HTTPSConnectionPool(host='show.bilibili.com', port=443): Max retries exceeded with url: /api/ticket/project/getV2?version=134&id=83649&project_id=83649 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

**Comment by mikumifa** [comment]
等一下2.6.0 按道理这个报错还是你得cookie有问题
