### ISSUE TITLE
呃呃

### ISSUE THREAD

**Issue by BGLin1** [mikumifa/biliTickerBuy#7]
呃呃能不能写下readme 逼养的不是程序员根本不会用的 你指望他们会自己安库阿

**Comment by mikumifa** [comment]
在考虑, 但是最近没空,等等贴几个博客

**Comment by BGLin1** [comment]
> 在考虑, 但是最近没空,等等贴几个博客

我来写喵

**Comment by ChisatoNishikigi73** [comment]
可以吧res贴上去，带环境的

**Comment by 3va1in** [comment]
3Q

**Comment by xianyu23333** [comment]
> 在考虑, 但是最近没空,等等贴几个博客

大佬，快要抢票了，写出来了吗😭。
