### ISSUE TITLE
[Feature]: 优化建议

### ISSUE THREAD

**Issue by z9394974** [mikumifa/biliTickerBuy#87]
### 这是一个？

现有功能优化

### 详细描述

目前我个人使用是2024年6月6日下载的版本，有几个小建议希望大佬能考虑下：1.新的版本似乎不支持购买张数的选择（我看之前指引是可以选张数的），能否恢复？2.如果是一个项目有多个演出场次（比如一个艺人12：00一场，18：00一场），能否考虑支持在一个配置文件内支持抢多个场次，这样不用复制配置文件，节约时间 3.如果是支持选座的演出，有没可能支持到选座（给个默认配置选定位置范围就行）？目前B站演出里面有这个有支持演出选座的（https://show.bilibili.com/platform/detail.html?id=84520&from=pc_search）。如有打搅，万分抱歉！

**Comment by mikumifa** [comment]
选多少个实名就是选多少张门票

**Comment by mikumifa** [comment]
选座再计划之中，自动切换配置文件也在计划中

**Comment by FGstyleZ** [comment]
能不能抢完一张还能继续抢，现在要付完上一单才能重新开始抢

**Comment by YourComputer011** [comment]
> 能不能抢完一张还能继续抢，现在要付完上一单才能重新开始抢

刚刚问过w，详情见上一个issue

**Comment by mikumifa** [comment]
> > 能不能抢完一张还能继续抢，现在要付完上一单才能重新开始抢
> 
> 刚刚问过w，详情见上一个issue

现在先抢完开个新的exe再抢吧，这个功能估计要到bw之后才能出来，因为我要全测试一遍没问题才会弄到正式版

**Comment by YourComputer011** [comment]
> > > 能不能抢完一张还能继续抢，现在要付完上一单才能重新开始抢
> > 
> > 
> > 刚刚问过w，详情见上一个issue
> 
> 现在先抢完开个新的exe再抢吧，这个功能估计要到bw之后才能出来，因为我要全测试一遍没问题才会弄到正式版

我实际粗略测试了一下，打开多个网页发送多个抢票请求，即可按照发送请求的顺序依次抢票，不知道这个方法稳不稳定

**Comment by mikumifa** [comment]
> > > > 能不能抢完一张还能继续抢，现在要付完上一单才能重新开始抢
> > > 
> > > 
> > > 刚刚问过w，详情见上一个issue
> > 
> > 
> > 现在先抢完开个新的exe再抢吧，这个功能估计要到bw之后才能出来，因为我要全测试一遍没问题才会弄到正式版
> 
> 我实际粗略测试了一下，打开多个网页发送多个抢票请求，即可按照发送请求的顺序依次抢票，不知道这个方法稳不稳定

抢完一张还能继续抢。。。。。。

b站必须一个账号付完款，或者订单取消才能重新抢

准备多个账号应该算是一个比较好的方法吧

打开多个网页发送多个抢票请求，用的还是一个账号，抢同一个票还是会出问题

注意到时候账号别选错了

**Comment by YourComputer011** [comment]
> > > > > 能不能抢完一张还能继续抢，现在要付完上一单才能重新开始抢
> > > > 
> > > > 
> > > > 刚刚问过w，详情见上一个issue
> > > 
> > > 
> > > 现在先抢完开个新的exe再抢吧，这个功能估计要到bw之后才能出来，因为我要全测试一遍没问题才会弄到正式版
> > 
> > 
> > 我实际粗略测试了一下，打开多个网页发送多个抢票请求，即可按照发送请求的顺序依次抢票，不知道这个方法稳不稳定
> 
> 抢完一张还能继续抢。。。。。。
> 
> b站必须一个账号付完款，或者订单取消才能重新抢
> 
> 准备多个账号应该算是一个比较好的方法吧
> 
> 打开多个网页发送多个抢票请求，用的还是一个账号，抢同一个票还是会出问题
> 
> 注意到时候账号别选错了

好吧我的问题（捂脸）
我在测试的时候两次抢票间隔了一分钟，在这一分钟里我取消了前一个订单

**Comment by mikumifa** [comment]
我不想把程序设计的太复杂，我想要让程序变得更简单，不易出错

程序的功能越简单，越清晰越好

怎么使用全靠你们自己安排

通过多开几个程序能够完成的功能我觉得都不急着加上去（现在的程序在五一的崩铁没啥问题，不打算到bw时候把程序改错了

可能没有抢票切换的逻辑会让你们会觉得用起来会很麻烦， 但是功能加上去之后，冗余的界面会让你们觉得更麻烦 （而且还会容易用错

**Comment by LFishThighL** [comment]
不知道后面会加上余量票功能吗

**Comment by mikumifa** [comment]
> 不知道后面会加上余量票功能吗

一直扫，不就是余票么

**Comment by LFishThighL** [comment]
> > 不知道后面会加上余量票功能吗
> 
> 一直扫，不就是余票么

还没开票前或者开票后可以扫到库存的意思，了解了，感谢

**Comment by mikumifa** [comment]
选座 暂时割掉，接口太复杂了，我也不好展示出来
