### ISSUE TITLE
[Feature]: Release里发布linux的可执行文件

### ISSUE THREAD

**Issue by haohao927** [mikumifa/biliTickerBuy#90]
### 这是一个？

新功能

### 详细描述

想挂在linux系统的云服务器上，奈何没有能力编译，希望能发布linux的可执行文件

**Comment by haohao927** [comment]
在win上把cookies导出然后再导入应该可以吧

**Comment by haohao927** [comment]
只不过的话这样好像要大改初始化的部分了，毕竟现在的逻辑是启动后就是登录

**Comment by mikumifa** [comment]
而且程序也有不少地方，是重庆才生效的，个人感觉没办法做到部署linux（程序是有状态的）

**Comment by mikumifa** [comment]
而且程序也有不少地方，是重启才生效的，个人感觉没办法做到部署linux（程序是有状态的）

**Comment by haohao927** [comment]
嗯嗯，如果难搞 麻烦的话就算了

**Comment by WittF** [comment]
用Linux-Debian12试了一下，直接克隆源码用python运行，可以生成抢票配置并创建订单显示付款码，过码没试
