### ISSUE TITLE
[Feature]: 局域网内其他设备访问 

### ISSUE THREAD

**Issue by 0Miku0831** [mikumifa/biliTickerBuy#92]
### 这是一个？

现有功能优化

### 详细描述

启动项目提示：“To create a public link, set share=True in launch()",。我有公网IP，ipv4,想通过端口转发的方式让朋友帮我点验证码，请问这个函数在哪里更改呢？有Windows 图形化界面

**Comment by mikumifa** [comment]
这个要改源代码。。。

**Comment by mikumifa** [comment]
提前说明一下，验证码只能同时一个人用，不存在2个人联机一起解开验证码的

**Comment by 0Miku0831** [comment]
> 这个要改源代码。。。

把源码下载重新编译吗😳

**Comment by mikumifa** [comment]
差不多

**Comment by 0Miku0831** [comment]
> 提前说明一下，验证码只能同时一个人用，不存在2个人联机一起解开验证码的

我不确定我到时候能不能在电脑跟前 所以想通过端口转发的方式在外面访问

**Comment by mikumifa** [comment]
这倒是可以，下一次更新会加上去

**Comment by 0Miku0831** [comment]
> 这倒是可以，下一次更新会加上去

好的 多谢您了 bw票好难抢😭
